"""The signet's model, in Python — the same marks assets/js/cf-signet.js draws.

WHY IT IS A PORT AND NOT A SECOND DESIGN. `cf-signet.js` says in its own header
why its hash is FNV-1a: "Chosen because it is eight lines, has no seed table
and gives the same answer in Python — which matters the day the Open Graph
plates are generated by a build script rather than by this file." This is that
day. A page's share plate and the mark that page prints inline have to be the
SAME mark, or the plate stops being that page's face and becomes a second
decoration.

Everything a seed decides lives here: the 32-bit hash, the xorshift stream, the
Fisher-Yates over the fixed multiset, and the nine plots in paint order. What a
seed does NOT decide — the lattice, the multiset, the ramp, which tower is lit
— is quoted from the JavaScript rather than re-invented, and
`scripts/check-signet-parity.py` reads both files and fails if they disagree
about any of it.

WHAT IS DELIBERATELY NOT HERE. The SVG. This module returns geometry; the
plate rasterises it and the browser gets its copy from the JavaScript. Two
emitters for one model is the drift the parity check exists to catch, so there
is exactly one of each: one model in each language, one emitter in each
language, and a check that binds the models.

SEEDS ARE ASCII. `charCodeAt` walks UTF-16 code units and `ord` walks code
points; they agree below U+10000 and every seed in this system is a URL path.
`seed_bytes` asserts that rather than trusting it.
"""

# The lattice. Quoted from cf-signet.js — see the parity check.
W, H, STOREY, N = 18, 9, 18, 3
CX, CY = 60, 69
VIEWBOX = 120

# The fixed multiset: three empty plots, two towers at full height, always.
HEIGHTS = [0, 0, 0, 1, 1, 2, 2, 3, 3]
PEAK = 3

# The family's ramp on the near rake, waypoint included. Quoted from
# cf-signet.js in fractions rather than percentages — see the parity check.
#
# THE ONE RAMP IN THIS RASTERISER THAT IS NOT DERIVED, and the contrast is two
# functions away: plate.py's wash_stops() reads --wash-stops out of tokens.css
# on every run rather than pasting four numbers, precisely so the plate and the
# page cannot part. This table cannot do that, and should not — it is one half
# of a two-language model that check-signet-parity.py holds byte for byte, and
# a python that read tokens.css would no longer be the same model the
# javascript is.
#
# So it is held from outside instead: check-gradient-family.py reads this list
# and recomputes the waypoint's offset and colour from lime and Glas. Until it
# did, this ramp and its twin were bound only to EACH OTHER — move --cf-lime
# and both would go stale in step with parity still green.
STOPS = [(0.0, "#E1FF00"), (0.061, "#DBFC60"), (0.32, "#C5EBE2"), (1.0, "#CFCFCF")]

# The three tones off the manual's isometric stack. Light from the upper left.
FACE_TOP = "#DADADA"
FACE_LEFT = "#CFCFCF"
FACE_RIGHT = "#C4C4C4"


def seed_bytes(seed):
    s = str(seed)
    for ch in s:
        if ord(ch) > 0xFFFF:
            raise ValueError("seed %r leaves the BMP; JS and Python would diverge" % s)
    return s


def hash32(seed):
    """FNV-1a, 32-bit. Byte for byte what cf-signet.js computes."""
    h = 0x811C9DC5
    for ch in seed_bytes(seed):
        h ^= ord(ch)
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def stream(seed):
    """xorshift32, seeded by the hash. Every step is a 32-bit integer op, which
    is what makes it give the same sequence in both languages."""
    state = [hash32(seed) or 0x9E3779B9]

    def nxt():
        s = state[0]
        s = (s ^ (s << 13)) & 0xFFFFFFFF
        s ^= s >> 17
        s = (s ^ (s << 5)) & 0xFFFFFFFF
        state[0] = s
        return s

    return nxt


def heights(seed):
    """Fisher-Yates over the multiset — the JS loop, index for index."""
    nxt = stream(seed)
    a = list(HEIGHTS)
    for i in range(len(a) - 1, 0, -1):
        j = nxt() % (i + 1)
        a[i], a[j] = a[j], a[i]
    return a


def plots(seed):
    """The nine plots in paint order: back to front by depth, left to right in
    a depth. Sorting here is what makes occlusion a property of the model."""
    h = heights(seed)
    out = []
    for a in range(N):
        for b in range(N):
            out.append({
                "a": a, "b": b, "d": a + b, "h": h[a * N + b],
                "x": CX + (a - b) * W,
                "y": CY + (a + b) * H,
            })
    out.sort(key=lambda p: (p["d"], p["a"]))
    return out


def lit_plot(order):
    """The frontmost full-height tower. The list is already back to front, so
    it is the last one that reaches PEAK — no comparison, and no way for the
    rule and the paint order to come apart."""
    found = None
    for p in order:
        if p["h"] == PEAK:
            found = p
    return found


def faces(seed, lit=True):
    """Every face of one mark, in paint order, in the 120 x 120 viewBox.

    Yields dicts: {'kind', 'points'} where kind is one of

        plot   an empty plot's ground rhombus — dashed contour, no fill
        left   right   top     a face in one of the three greys
        lit    the one face carrying the ramp
        dot    a construction dot on the lit face, as (cx, cy, r)

    The caller decides paint; this decides shape and order, which is the same
    split cf-signet.js makes between its geometry and its CSS classes.
    """
    order = plots(seed)
    target = lit_plot(order) if lit else None
    for p in order:
        x, y, h = p["x"], p["y"], p["h"]
        if h == 0:
            yield {"kind": "plot",
                   "points": [(x, y - H), (x + W, y), (x, y + H), (x - W, y)]}
            continue
        top = y - h * STOREY
        yield {"kind": "left",
               "points": [(x - W, top), (x, top + H), (x, y + H), (x - W, y)]}
        yield {"kind": "right",
               "points": [(x + W, top), (x, top + H), (x, y + H), (x + W, y)]}
        cap = [(x, top - H), (x + W, top), (x, top + H), (x - W, top)]
        if p is target:
            yield {"kind": "lit", "points": cap, "x": x, "top": top}
            for cx, cy in ((x, top - H), (x + W, top), (x, top + H), (x - W, top)):
                yield {"kind": "dot", "at": (cx, cy, 1.5)}
        else:
            yield {"kind": "top", "points": cap}


def ramp_axis(x, top):
    """The lit face's gradient endpoints, in viewBox units.

    The designer's own vector off geometry.html's stack, scaled by 0.15 — dx 1
    over dy 2, which is 63.43 deg and a sanctioned angle. Restated here because
    the plate draws the face, and taken from the same two numbers the JS uses.
    """
    return (x - 7.5, top - 12), (x + 4.5, top + 12)
