#!/usr/bin/env python3
"""The English pages under design-system/patterns/en/, generated from the German ones.

WHY A GENERATOR AND NOT SIXTEEN MORE PAGES. scripts/build-site.py already
settled this argument for the root of the repository, in its own header: "a
copy of 8 500 lines of HTML, edited hourly on one side, is a drift the
repository would notice about a week late." An English edition is that same
copy again, and the hourly side is not hypothetical — five scheduled routines
run against design-system/patterns/landing-page.html and merge their own work.
A hand-written English landing page would be a generation behind by lunchtime.

So the English pages are output, the same way the root pages are output, and
`--check` holds them to their source. What is authored by hand is the one file
that has to be: design-system/i18n/en.json, the catalogue of German copy and
its English counterpart. Markup, class names, comments, page-local <style> and
<script>, the isometric drawings, the act structure — none of it is duplicated.
It comes through from the German page byte for byte, and only the words change.

WHY patterns/en/ AND NOT A SIBLING SUFFIX. Every scripts/check-*.py reads the
pattern pages as `glob("*.html")` — eighty-two of them, none recursive. A
subdirectory is therefore the one place a generated page can live inside
design-system/patterns/ without doubling the census every one of those checks
keeps: check-glass-budget.py's PAGE_BUDGET, check-class-provenance.py's
per-page exemptions, check-breakpoints.py's register. The English pages are the
German pages with the words changed; they carry the same glass, the same
classes and the same thresholds by construction, and asserting that twice would
only mean editing two tables whenever one page changes.

It is also what makes the links work with no rewriting at all. patterns/en/
mirrors patterns/, so `href="kontakt.html"` on an English page lands on the
English contact page, and the same string ships to /en/kontakt.html at the
root. The only href this file writes is the one between the editions.

THE EDITS, and nothing else:

  LANG      <html lang="de"> → <html lang="en">.

  ASSETS    `../assets/…` → `../../assets/…`, and `../index.html` (the preview
            nav back into the documentation) → `../../index.html`. One
            directory deeper, one `../` more. No copy of any asset.

  SWITCH    The nav's language control, which is written on the German page as
            a link to `en/<name>.html` and becomes a link to `../<name>.html`
            here, with its two labels swapped: the English page marks EN as
            where you are and points at DE. Both editions carry the same
            control in the same place, so the reader can always get back.

  ALTERNATE The <link rel="alternate" hreflang> pair in the head, which points
            each edition at the other and at itself, flips the same way.

  COPY      Every run of text, and every translatable attribute, replaced from
            the catalogue. A German string with no entry is a build failure —
            not a page that ships with a German sentence in it.

WHAT IT DOES NOT TOUCH. HTML comments. They are the design system's notes to
itself about why a rule is written the way it is, they are read in the
repository rather than on the page, and translating them would fork the one
copy of that reasoning. Whitespace, attribute order, indentation, the page-local
<style> and <script> blocks, every id and every class come through unchanged, so
`diff patterns/kontakt.html patterns/en/kontakt.html` is a list of sentences.

USAGE

    python3 scripts/build-i18n.py             # write design-system/patterns/en/
    python3 scripts/build-i18n.py --check     # fail if any page is stale or missing
    python3 scripts/build-i18n.py --extract   # print every string with no entry
    python3 scripts/build-i18n.py -v          # name every page, not only the changed ones
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATTERNS = ROOT / "design-system" / "patterns"
OUT = PATTERNS / "en"
CATALOGUE = ROOT / "design-system" / "i18n" / "en.json"

BANNER = (
    "<!-- GENERATED — DO NOT EDIT THIS FILE.\n"
    "     The English edition is built from the German pattern page. This page is\n"
    "     design-system/patterns/%s with its words replaced from\n"
    "     design-system/i18n/en.json. Change the German page or the catalogue,\n"
    "     then run:\n"
    "\n"
    "         python3 scripts/build-i18n.py\n"
    "\n"
    "     CI runs `--check`, so an edit made here is lost rather than shipped. -->\n"
)

DOCTYPE = "<!DOCTYPE html>\n"

# Regions whose text is not copy. <script> and <style> hold code; a comment holds
# the system's notes to itself; <pre>, <code> and <textarea> hold specimens that
# are quoted rather than read. The JSON-LD block is a <script> and is handled by
# its own pass below, because its *values* are copy even though its keys are not.
OPAQUE = re.compile(
    r"<!--.*?-->"
    r"|<script\b[^>]*>.*?</script\s*>"
    r"|<style\b[^>]*>.*?</style\s*>"
    r"|<pre\b[^>]*>.*?</pre\s*>"
    r"|<textarea\b[^>]*>.*?</textarea\s*>"
    # The language switch is not copy in either direction: its label is the
    # name of the other edition, and SWITCH below writes both sides of it.
    r"|<a class=\"cf-nav__lang\".*?</a\s*>",
    re.S | re.I,
)

TAG = re.compile(r"<[^>]*>", re.S)

# The attributes that carry copy. `content` is qualified below — it is copy on
# <meta name="description"> and a number everywhere else.
ATTRS = ("alt", "title", "placeholder", "aria-label", "value", "label")
ATTR_RE = re.compile(r'\b(%s)="([^"]*)"' % "|".join(ATTRS))
DESC_RE = re.compile(r'(<meta\s+name="description"\s+content=")([^"]*)(")', re.I)

# A run of text is copy if it holds two adjacent letters. `01`, `·`, `—` and
# `/` are drawing, not language, and asking the catalogue for them would fill it
# with punctuation mapped to itself.
HAS_WORD = re.compile(r"[^\W\d_]{2,}", re.U)

# The JSON-LD strings that are copy. Everything else in that block — dates,
# URLs, currency codes, @type — is data.
LD_COPY_KEYS = {"title", "description", "name", "value", "jobBenefits", "responsibilities",
                "qualifications", "employmentType", "addressLocality", "addressRegion"}


def load_catalogue():
    """The catalogue, plus the per-page overrides folded in on demand.

    Almost every German string has one English counterpart wherever it appears,
    and a single flat table is what makes that true — one nav, one footer, one
    consent banner, translated once for sixteen pages. The exception is the
    word that is two words. `Telemetrie` is a topic label in the News filter,
    where it is a capitalised noun, and it is also the marked search term
    inside a sentence on /suche, where it is not. `"@pages"` is where that
    difference is written down, keyed by the page it applies to, and it is
    deliberately awkward to reach for: a second entry there is a claim that the
    same sentence means two things, which is nearly always a sign that the
    German said two things."""
    if not CATALOGUE.exists():
        sys.exit("no catalogue at %s — nothing to translate with" % CATALOGUE.relative_to(ROOT))
    raw = json.loads(CATALOGUE.read_text(encoding="utf-8"))
    pages = raw.pop("@pages", {})
    return raw, pages


def for_page(cat, pages, name):
    if name not in pages:
        return cat
    merged = dict(cat)
    merged.update(pages[name])
    return merged


def key_of(text):
    """The catalogue key for a run of text: its words, with the layout taken out.

    A pattern page wraps its paragraphs, so the same sentence is one line on one
    page and three on another. The key is the sentence."""
    return re.sub(r"\s+", " ", text).strip()


USED = set()


def translate_run(text, cat, missing):
    """Replace one run of text, keeping the whitespace that surrounded it."""
    k = key_of(text)
    if not k or not HAS_WORD.search(k):
        return text
    if k not in cat:
        missing.add(k)
        return text
    USED.add(k)
    en = cat[k]
    lead = text[: len(text) - len(text.lstrip())]
    trail = text[len(text.rstrip()):]
    return lead + en + trail


def translate_attrs(tag, cat, missing):
    def sub(m):
        name, val = m.group(1), m.group(2)
        k = key_of(val)
        if not k or not HAS_WORD.search(k):
            return m.group(0)
        if k not in cat:
            missing.add(k)
            return m.group(0)
        USED.add(k)
        return '%s="%s"' % (name, cat[k])
    return ATTR_RE.sub(sub, tag)


def translate_ld(block, cat, missing):
    """The JobPosting block. Its string values are copy; its keys are not."""
    def sub(m):
        key, val = m.group(1), m.group(2)
        if key not in LD_COPY_KEYS:
            return m.group(0)
        k = key_of(val)
        if not k or not HAS_WORD.search(k):
            return m.group(0)
        if k not in cat:
            missing.add(k)
            return m.group(0)
        USED.add(k)
        return '"%s": "%s"' % (key, cat[k].replace('"', '\\"'))
    return re.sub(r'"([A-Za-z]+)":\s*"((?:[^"\\]|\\.)*)"', sub, block)


LD_BLOCK = re.compile(r'(<script\b[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script\s*>)', re.S | re.I)


def translate(src, cat, missing):
    """Walk the document, translating text runs and attributes, leaving the rest."""
    out = []
    pos = 0
    for m in OPAQUE.finditer(src):
        out.append(translate_markup(src[pos:m.start()], cat, missing))
        out.append(m.group(0))
        pos = m.end()
    out.append(translate_markup(src[pos:], cat, missing))
    doc = "".join(out)
    # The JSON-LD block was masked as a <script>; translate its values now.
    doc = LD_BLOCK.sub(lambda m: m.group(1) + translate_ld(m.group(2), cat, missing) + m.group(3), doc)

    # The description meta, which ATTRS deliberately leaves alone: `content` is
    # copy on this one tag and a number, a URL or a viewport on every other.
    def desc(m):
        k = key_of(m.group(2))
        if not k or not HAS_WORD.search(k):
            return m.group(0)
        if k not in cat:
            missing.add(k)
            return m.group(0)
        USED.add(k)
        return m.group(1) + cat[k] + m.group(3)
    return DESC_RE.sub(desc, doc)


def translate_markup(chunk, cat, missing):
    """A region with no opaque blocks in it: alternating tags and text."""
    out = []
    pos = 0
    for m in TAG.finditer(chunk):
        out.append(translate_run(chunk[pos:m.start()], cat, missing))
        out.append(translate_attrs(m.group(0), cat, missing))
        pos = m.end()
    out.append(translate_run(chunk[pos:], cat, missing))
    return "".join(out)


# ---------------------------------------------------------------------------
# The four structural edits.

LANG = ('<html lang="de">', '<html lang="en">')

# ASSETS. One directory deeper than the German page, so one `../` more. The
# preview nav back into the documentation moves with them.
ASSETS = re.compile(r'(href|src|poster)="\.\./(assets/|index\.html)')

# SWITCH. Written whole rather than patched, because every part of it flips:
# the target, the language it declares, the language its label is written in,
# and the label. The German page offers English and the English page offers
# German, and neither sentence is a translation of the other — "Auf Deutsch
# wechseln" is what a German reader is owed, and it is what the English page
# has to say, in German, to a reader who cannot read the page it is on.
SWITCH = re.compile(r'<a class="cf-nav__lang" href="en/([a-z0-9-]+\.html)"'
                    r' hreflang="en" lang="en" aria-label="[^"]*">[^<]*</a>')
SWITCH_EN = ('<a class="cf-nav__lang" href="../%s"'
             ' hreflang="de" lang="de" aria-label="Auf Deutsch wechseln">DE</a>')

# ALTERNATE. Both editions are named on both pages, each one pointing at
# itself as well as at the other — a self-referencing alternate is what tells
# a crawler the set is complete. From inside en/ the German page is one level
# up and the English page is the file beside it.
ALT_EN = re.compile(r'(<link rel="alternate" hreflang="en" href=")en/([a-z0-9-]+\.html">)')
ALT_DE = re.compile(r'(<link rel="alternate" hreflang="de" href=")([a-z0-9-]+\.html">)')

# ACTION. The contact form posts across origins to the Worker, because the site
# is on GitHub Pages while the relaunch is being built and Pages answers a POST
# with 405. That address is absolute, and an absolute address does not re-point
# itself the way the relative one did: `kontakt.html#fehler` used to mean the
# English page as soon as it sat in en/, and this one has to be told.
#
# The host is deliberately not written here — it is matched and carried over —
# so this file has no opinion about which Worker the form talks to, and the
# cutover changes one line of one pattern page rather than two files.
#
# Only kontakt.html has a form, so unlike the four edits above this one is
# allowed to match nothing.
ACTION = re.compile(r'(action="https://[^"]+)/kontakt\.html#fehler"')
ACTION_EN = r'\1/en/kontakt.html#fehler"'


def once(doc, pattern, repl, name, what):
    doc, n = pattern.subn(repl, doc)
    if n != 1:
        sys.exit("%s: expected one %s, found %d" % (name, what, n))
    return doc


def structural(doc, name):
    if LANG[0] not in doc:
        sys.exit("%s: no <html lang=\"de\"> to flip" % name)
    doc = doc.replace(LANG[0], LANG[1], 1)

    doc, n = ASSETS.subn(r'\1="../../\2', doc)
    if n == 0:
        sys.exit("%s: no ../assets/ or ../index.html reference to re-root" % name)

    doc = once(doc, ALT_EN, r'\1\2', name, 'hreflang="en" alternate')
    doc = once(doc, ALT_DE, r'\1../\2', name, 'hreflang="de" alternate')

    doc, n = ACTION.subn(ACTION_EN, doc)
    if n > 1:
        sys.exit("%s: expected at most one cross-origin form action, found %d" % (name, n))
    return doc


def build(doc, name, cat, missing):
    doc = structural(doc, name)
    doc = translate(doc, cat, missing)
    # After the copy pass, because the switch is masked from it: the label is
    # a language name, not a sentence the catalogue has an opinion about.
    doc = once(doc, SWITCH, lambda m: SWITCH_EN % m.group(1), name, ".cf-nav__lang link")
    if not doc.startswith(DOCTYPE):
        sys.exit("%s: does not open with a doctype" % name)
    return DOCTYPE + BANNER % name + doc[len(DOCTYPE):]


def main(argv):
    check = "--check" in argv
    extract = "--extract" in argv
    verbose = "-v" in argv or "--verbose" in argv

    cat, overrides = ({}, {}) if extract and not CATALOGUE.exists() else load_catalogue()
    pages = sorted(p for p in PATTERNS.glob("*.html"))
    missing = set()
    stale, wrote = [], []

    for src in pages:
        doc = build(src.read_text(encoding="utf-8"), src.name,
                    for_page(cat, overrides, src.name), missing)
        if extract:
            continue
        dst = OUT / src.name
        if dst.exists() and dst.read_text(encoding="utf-8") == doc:
            if verbose:
                print("  ok      en/%s" % src.name)
            continue
        if check:
            stale.append(src.name)
            continue
        OUT.mkdir(parents=True, exist_ok=True)
        dst.write_text(doc, encoding="utf-8")
        wrote.append(src.name)

    if extract:
        for k in sorted(missing):
            print(json.dumps(k, ensure_ascii=False) + ": " + json.dumps("", ensure_ascii=False) + ",")
        print("\n%d strings with no entry" % len(missing), file=sys.stderr)
        return 0

    if missing:
        for k in sorted(missing):
            print("  UNTRANSLATED  %s" % k, file=sys.stderr)
        print("\n%d strings have no entry in %s. Run --extract."
              % (len(missing), CATALOGUE.relative_to(ROOT)), file=sys.stderr)
        return 1

    # An entry nothing asked for is nearly always a key typed slightly wrong —
    # one that will read as UNTRANSLATED at the same time. Reported together,
    # the pair names itself.
    unused = set(cat) - USED
    for k in sorted(unused):
        print("  UNUSED    %s" % k, file=sys.stderr)
    if unused:
        print("\n%d catalogue entries match no string on any page." % len(unused),
              file=sys.stderr)
        return 1

    # Nothing under en/ that is not generated from a page beside it.
    if OUT.exists():
        owned = {p.name for p in pages}
        for f in sorted(OUT.glob("*.html")):
            if f.name not in owned:
                print("  UNOWNED   en/%s — no design-system/patterns/%s to build it from"
                      % (f.name, f.name), file=sys.stderr)
                return 1

    if check:
        if stale:
            for n in stale:
                print("  STALE     en/%s" % n, file=sys.stderr)
            print("\n%d English page(s) do not match their source. Run "
                  "python3 scripts/build-i18n.py" % len(stale), file=sys.stderr)
            return 1
        print("%d English pages match their source." % len(pages))
        return 0

    for n in wrote:
        print("  wrote     en/%s" % n)
    print("%d English page(s) written, %d unchanged." % (len(wrote), len(pages) - len(wrote)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
