#!/usr/bin/env python3
"""One reading page per post, generated from content/news/ and the specimen.

WHAT WAS WRONG. Every card in the archive linked to blog-artikel.html. Eighteen
headlines, one destination: click "Wärmepumpen im Winter" and read about digital
twins. The card said one thing and the page said another — the same fault
build-news.py was written for one level up, where three counters claimed a
hundred and seventy-one articles that did not exist, and it is worse here
because the reader has already committed a click to it.

SO A POST WITH TEXT IS A PAGE. content/news/ holds one file per post; a post
that carries text carries it in both languages, divided by a line; and this
script writes `beitrag-<name>.html` for each of them, in German beside the
patterns and in English under patterns/en/. build-news.py links the card to the
page it knows this script will write — page_name() is defined once, there, and
read here, so the two cannot disagree about which posts have a page.

A POST WITHOUT TEXT GETS NO PAGE, and that is not an omission. The archive was
seeded from the cards of the mock-up: eighteen entries that are a headline, a
date and a reading time, with nothing written behind them. A generated page for
one of those would state "6 Min. Lesezeit" over an apology, which is the
original fault with an extra step. Their cards stay in the archive and stay
listings — build-news.py draws them as a <span> — and the moment somebody
writes the text, in Notion or in the file, the card becomes a link and this
script writes the page. Nothing else has to change.

THE FURNITURE IS NOT COPIED, IT IS READ. blog-artikel.html is the specimen of
the reading surface and it is written by hand, with figures, a plot, a table
and a pull quote that the markdown a post is written in cannot express. This
script reads that file and replaces the nine regions fenced by `article:…`
comments — the title, the byline, the text, the contents rail, what follows.
Everything outside those fences comes through untouched: the head, the consent
banner, the navigation, the article grid, the footer. A change to the reading
surface is made once, on the specimen, and every published article has it on
the next build.

AND THE ENGLISH EDITION IS THE SAME SPLICE ON THE TRANSLATED SPECIMEN.
build-i18n.py has already turned blog-artikel.html into en/blog-artikel.html —
the nav, the consent text and the footer are translated there, once, for
sixteen pages — and HTML comments are the one thing it never touches, so the
fences survive into the English file and mark the same nine regions. The
English page is that file with the post's English text spliced in. No article
sentence ever enters design-system/i18n/en.json: a catalogue is for the copy
that repeats across pages, and an article's text appears exactly once. Which is
also why this runs AFTER build-i18n.py — it needs the translated specimen —
and why build-i18n.py skips `beitrag-*.html`: those pages are already in both
languages before it looks at them.

    python3 scripts/build-articles.py           # write the article pages
    python3 scripts/build-articles.py --check   # fail if any is stale or orphaned
    python3 scripts/build-articles.py -v        # name every page, not only the new ones

stdlib only, no build step, no dependency. Same python3 that serves the pages.
"""

import argparse
import importlib.util
import pathlib
import re
import sys
import textwrap
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parents[1]
PATTERNS = ROOT / "design-system" / "patterns"
EN = PATTERNS / "en"
SPECIMEN = "blog-artikel.html"

BANNER = (
    "<!-- GENERATED — DO NOT EDIT THIS FILE.\n"
    "     One post of the news archive, on the reading surface of\n"
    "     design-system/patterns/%s. The text is content/news/%s;\n"
    "     everything around it is that page. Change the post or the specimen,\n"
    "     then run:\n"
    "\n"
    "         python3 scripts/build-articles.py\n"
    "\n"
    "     CI runs `--check`, so an edit made here is lost rather than shipped. -->\n"
)

DOCTYPE = "<!DOCTYPE html>\n"

# The two words that name what kind of page this is, in the two editions. The
# specimen says "Analyse"/"Analysis" because it is one; a post does not declare
# a genre, and inventing one per post would be metadata written by a generator
# and read as a claim by a reader.
KIND = {"de": "Beitrag", "en": "Post"}
READ = {"de": "%s Min. Lesezeit", "en": "%s min read"}
CONTENTS = {"de": "Inhalt", "en": "Contents"}
MORE = {"de": "%d von %d", "en": "%d of %d"}

# WHO WROTE IT. The archive carries an author's name and nothing else, and this
# is where that name gets the job title ueber-uns.html shows for the same
# person. They are English titles on both editions, which is how that page
# already carries them, and lang="en" is what says so. A name that is not here
# still gets its byline — it gets the name alone, which is what the record has.
ROLE = {
    "Simon Deussen":     "Founder &amp; Managing Partner",
    "Daniel Tremer":     "Managing Partner",
    "Piet Brömmel":      "Data Engineer",
    "Henry Beiker":      "Data Engineer",
    "Robin Marzucca":    "Data Engineer",
    "Marie Ernø-Møller": "Data Engineer",
    "Birk Burghardt":    "Data Engineer",
}

# AND NO PHOTOGRAPH, WHICH IS DELIBERATE AND IS NOT PERMANENT. The byline box is
# a fixed 3rem, so scripts/check-image-scale.py holds whatever goes in it to a
# file between 96 and 144 device pixels — the 640 x 800 studio portraits are 4.4 x
# over that ceiling and are the fault that check was written for. The only files
# inside the window are portrait-01…04-144.jpg, and they are from the placeholder
# era: portrait-01 is not the person in simon.jpg and portrait-02 is not the
# person in daniel.jpg, compared side by side. There is no 144 px derivative
# filed under a person's name, and a byline is the one place a face is a claim
# about who wrote something. So a generated byline is a name and a role until
# those derivatives exist, at which point one line here gives every article a
# face. (blog-artikel.html still carries portrait-02-144.jpg under Daniel
# Tremer's name — that is the specimen's own stale claim, and it is not this
# script's to fix in passing.)


def fail(msg):
    print("build-articles: " + msg, file=sys.stderr)
    sys.exit(1)


IMG = ROOT / "design-system" / "assets" / "img"


def intrinsic(path):
    """A raster file's real pixel size, read from its header.

    scripts/check-image-scale.py owns this — "no decoder, no dependency" — and
    it is imported rather than written again because that file is also the one
    that FAILS on a width/height attribute which disagrees with the file. Two
    readers of a JPEG header would disagree about a progressive scan exactly
    once, and the check would be right and the page would be wrong.
    """
    spec = importlib.util.spec_from_file_location(
        "cf_image_scale", pathlib.Path(__file__).with_name("check-image-scale.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.intrinsic(str(path))


def store():
    """build-news.py, imported rather than copied.

    It owns content/news/ — the fields, the two-language body, the page name a
    post's card links to. A second reader of the same files would be a second
    opinion about what a post is, and the first thing the two would disagree
    about is which posts have a page at all.
    """
    spec = importlib.util.spec_from_file_location(
        "cf_build_news", pathlib.Path(__file__).with_name("build-news.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# --------------------------------------------------------------------------
# the regions
# --------------------------------------------------------------------------

FENCE = "<!-- article:%s -->"
FENCE_END = "<!-- /article:%s -->"


def splice(html, name, body, where):
    """Replace one fenced region, keeping the fences and their indentation.

    An empty body leaves the fences with nothing between them — which is what a
    post with no author, no topics or no siblings has to produce. The fences
    stay because they are what the next build reads.
    """
    start, end = FENCE % name, FENCE_END % name
    m = re.search(re.escape(start) + r".*?" + re.escape(end), html, re.S)
    if not m:
        fail("%s has no %s … %s region. The fences are how this script knows "
             "what belongs to the post and what belongs to the page."
             % (where, start, end))
    pad = re.match(r"[ \t]*", html[html.rfind("\n", 0, m.start()) + 1:m.start()]).group(0)
    text = body(pad) if callable(body) else body
    inner = "\n%s\n%s" % (text, pad) if text else "\n%s" % pad
    return html[:m.start()] + start + inner + end + html[m.end():]


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def inline(s):
    """The three inline forms an editor produces: a link, bold, code.

    Escaped first and marked up after, so a `&` in a URL is an entity and a
    `<` in the text is not a tag. Nothing here is a general markdown parser —
    it is the set of things Notion's rich text can carry into a paragraph.
    """
    out = esc(s)
    out = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", r'<a href="\2">\1</a>', out)
    out = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"`(.+?)`", r"<code>\1</code>", out)
    return out


def anchor(text):
    """A heading's id, and the fragment the contents rail links to.

    Built from the heading itself so the URL a reader copies out of the address
    bar says where they were. Each edition builds its own from its own heading:
    the German page's #datenfundament is #the-data-foundation on the English
    one, and a fragment in a language the page is not written in is a string
    nobody can check by looking.
    """
    s = text.lower()
    for a, b in (("ä", "ae"), ("ö", "oe"), ("ü", "ue"), ("ß", "ss")):
        s = s.replace(a, b)
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    s = re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", s)).strip("-")
    # Cut on a word. A fragment is read by people — it is what a shared link
    # ends in — and `#cop-ist-eine-momentaufnahme-jaz-ist-die-` is a heading
    # stopped mid-sentence with a hyphen hanging off it.
    if len(s) > 40:
        s = s[:40].rsplit("-", 1)[0]
    return s.strip("-")


def wrap(pad, opening, text, closing):
    """One block, set the way the specimen sets its paragraphs: the tags on
    their own lines and the text wrapped under them. A generated page is read
    in the repository as often as in a browser, and a paragraph on one 700
    character line is a diff nobody can review."""
    body = textwrap.fill(text, width=96 - len(pad),
                         initial_indent=pad + "  ", subsequent_indent=pad + "  ",
                         break_long_words=False, break_on_hyphens=False)
    return "%s%s\n%s\n%s%s" % (pad, opening, body, pad, closing)


def prose(bs, edition, pad):
    """The post's text, as the elements .cf-prose styles by name.

    The first block is the lead — set larger, and the paragraph the archive and
    the search results quote — which is why bodies() in build-news.py refuses a
    post that opens with a heading.
    """
    out = []
    for i, (kind, payload) in enumerate(bs):
        if kind == "p":
            cls = ' class="cf-article__lead"' if i == 0 else ""
            out.append(wrap(pad, "<p%s>" % cls, inline(payload), "</p>"))
        elif kind in ("h2", "h3"):
            out.append('%s<%s id="%s">%s</%s>'
                       % (pad, kind, anchor(payload), inline(payload), kind))
        elif kind == "img":
            out.append(picture(payload[0], payload[1], edition, pad))
        else:
            tag = "ul" if kind == "ul" else "ol"
            out.append("%s<%s>" % (pad, tag))
            for item in payload:
                out.append(wrap(pad + "  ", "<li>", inline(item), "</li>"))
            out.append("%s</%s>" % (pad, tag))
    return "\n".join(out)


def picture(path, caption, edition, pad):
    """One photograph, as a plate: `.cf-prose > figure` runs the full width.

    THREE THINGS ARE WRITTEN AND NONE OF THEM IS A CHOICE MADE HERE.

    `width` and `height` are the file's real pixel dimensions, read from its
    header. They are the aspect-ratio box the browser reserves before the bytes
    arrive — an article without them reflows under the reader's eye as each
    picture lands — and scripts/check-image-scale.py fails on a pair that
    disagrees with the file, which is what makes them worth writing at all.

    `alt` is empty because the caption is right underneath and says what the
    picture is. That is the W3C figure pattern, it is what
    scripts/check-a11y.py means by "write alt="" if it is decorative", and it
    is why build-news.py refuses a picture with no caption: the alternative is
    a screen reader reading the same sentence twice, or reading nothing.

    `loading="lazy"` because a picture below the fold in a piece somebody has
    not started reading is not worth a request yet — every other image on the
    site that is not the hero carries it for the same reason.

    AND THE PATH IS WRITTEN FOR THE EDITION IT IS ON. Every other asset
    reference on an English page got its second `../` from build-i18n.py, which
    never sees this markup: the English article is this text spliced into the
    already-translated specimen. Written with one `../` it resolved to nothing
    from patterns/en/, and build-site.py stopped the build for it — "a
    preview-only reference survived the edits" — which is the check doing its
    job on a path this file had to write itself.
    """
    up = "../../assets/img/" if edition == "en" else "../assets/img/"
    f = IMG / path
    if not f.exists():
        fail("%s does not exist. A post's picture is a file in the repository, "
             "downloaded from Notion by scripts/sync-news-notion.py — a page "
             "cannot link to one that is not there." % f.relative_to(ROOT))
    dims = intrinsic(f)
    if not dims:
        fail("%s: cannot read the pixel size out of this file's header. JPEG, "
             "PNG, WebP and GIF are what scripts/check-image-scale.py reads."
             % f.relative_to(ROOT))
    w, h = dims
    return ("%s<figure>\n"
            '%s  <img src="%s%s" alt="" width="%d" height="%d"\n'
            '%s       loading="lazy" decoding="async">\n'
            "%s\n"
            "%s</figure>"
            % (pad, pad, up, path, w, h, pad,
               wrap(pad + "  ", "<figcaption>", inline(caption), "</figcaption>"),
               pad))


def rail(bs, edition, pad):
    """The contents, from the piece's own h2s.

    Nothing at all when the piece has none. A rail listing one entry is a
    control that answers a question nobody asked, and an empty <ol> is a
    landmark a screen reader announces and then has nothing to read out.
    """
    heads = [p for k, p in bs if k == "h2"]
    if len(heads) < 2:
        return ""
    out = ['%s<nav aria-labelledby="inhaltsverzeichnis">' % pad,
           '%s  <p class="cf-article__toc-title" id="inhaltsverzeichnis">%s</p>'
           % (pad, CONTENTS[edition]),
           '%s  <ol class="cf-article__toc">' % pad]
    out += ['%s    <li><a href="#%s">%s</a></li>' % (pad, anchor(h), inline(h))
            for h in heads]
    out += ["%s  </ol>" % pad, "%s</nav>" % pad]
    return "\n".join(out)


def byline(post, pad):
    """The author, with the role ueber-uns.html carries for them.

    Nothing at all when the post names no author — an empty byline box above
    the text is a hole where a person should be.
    """
    who = post.get("autor")
    if not who:
        return ""
    out = ["%s<div>" % pad,
           '%s  <p class="cf-person__name">%s</p>' % (pad, esc(who))]
    if who in ROLE:
        out.append('%s  <p class="cf-person__role" lang="en">%s</p>' % (pad, ROLE[who]))
    out.append("%s</div>" % pad)
    return "\n".join(out)


def meta_line(post, edition, pad):
    """`Beitrag · 01.01.2026` and the reading time, the specimen's two spans.

    The date is written the way the edition's own archive writes it — dotted in
    German, `01 Jan 2026` in English — because the reader has just come from a
    card that said one of those two things.
    """
    news = post["_news"]
    shown = news.german(post["datum"]) if edition == "de" else news.en_meta(post["datum"])
    out = ['%s<span>%s · <time datetime="%s">%s</time></span>'
           % (pad, KIND[edition], post["datum"], shown)]
    if post.get("minuten"):
        out.append("%s<span>%s</span>" % (pad, READ[edition] % post["minuten"]))
    return "\n".join(out)


def head(post, edition, pad):
    """The title a tab shows and the description a result page quotes.

    The description is the lead's first sentences rather than a field of its
    own: a summary written separately is a summary that stops matching the
    piece, and every post already opens with the paragraph that says what it
    is about.
    """
    title = post["titel"] if edition == "de" else post["title"]
    lead = (post["text_de"] if edition == "de" else post["text_en"])[0][1]
    desc = summary(lead)
    return ('%s<title>%s — Control-F</title>\n'
            '%s<meta name="description" content="%s">'
            % (pad, esc(title), pad, esc(desc).replace('"', "&quot;")))


def summary(lead, limit=165):
    """The lead, cut to what a search result shows, on a sentence if it can be.

    Cut on a word at worst. A description that ends mid-word is the one part of
    a page a reader meets before they have decided to read it.
    """
    text = re.sub(r"\s+", " ", re.sub(r"[*`]|\[|\]\([^)]*\)", "", lead)).strip()
    if len(text) <= limit:
        return text
    cut = text[:limit]
    stop = max(cut.rfind(". "), cut.rfind("! "), cut.rfind("? "))
    if stop > limit * 0.5:
        return cut[:stop + 1]
    return cut[:cut.rfind(" ")].rstrip(",;:—-") + " …"


def crumb(post, edition, pad):
    """The breadcrumb's last step: the title without its subtitle.

    The specimen shortens "Digitale Zwillinge im Energiesektor: Simulation
    trifft Realität" to what stands before the colon, and that is the rule —
    a breadcrumb is a place, and the second half of a headline is an argument.
    """
    title = post["titel"] if edition == "de" else post["title"]
    short = title.split(":")[0].strip() if ":" in title else title
    if len(short) > 60:
        short = short[:57].rsplit(" ", 1)[0] + " …"
    return ('%s<span class="cf-breadcrumb__current" aria-current="page">%s</span>'
            % (pad, esc(short)))


def tags(post, edition, pad):
    """The post's topics, each a link into the archive filtered to it.

    THE WAY BACK OUT OF ONE ARTICLE IS THE ARCHIVE NARROWED TO ITS SUBJECT, and
    it is the reason the topics are on the post at all. The specimen has always
    drawn three of these chips under the text; every generated page drew none,
    because a post carried no topic to draw — the region was spliced empty and
    the reader who had just finished a piece about heat pumps was offered
    "Alle Beiträge" and nothing else.

    They point at news-thema-<slug>.html, which is where the chips on the
    archive point too. Not at a query string: the specimen said
    `news.html?thema=telemetrie` and no server answers that — the site is static
    files, and the link came back with the whole unfiltered archive.

    In the order the post writes them, which is the writer's order of
    importance. The archive's own chips are in the vocabulary's order instead;
    the two are different lists doing different jobs.
    """
    news = post["_news"]
    out = ['%s<ul class="cf-article__tags">' % pad]
    for slug, de, en, _prose in post["topics"]:
        out.append('%s  <li><a class="cf-article__tag" href="%s">%s</a></li>'
                   % (pad, news.thema_name(slug), esc(de if edition == "de" else en)))
    out.append("%s</ul>" % pad)
    return "\n".join(out)


def related(post, posts, edition, total, pad):
    """Up to three other posts that have a page, newest first.

    Only posts with a page. The section is called Weiterlesen and a card in it
    that leads nowhere is the fault this script exists to remove, drawn in the
    one place a reader has already agreed to keep reading.
    """
    news = post["_news"]
    others = [p for p in posts
              if p["file"] != post["file"] and news.page_name(p)][:3]
    if not others:
        return ""
    p2 = pad + "  "
    out = ['%s<section class="section section--flush" aria-labelledby="weiterlesen">' % pad,
           '%s<div class="container">' % p2,
           '%s  <div class="cf-section-header cf-section-header--flush">' % p2,
           '%s    <h2 class="cf-section-header__label" id="weiterlesen">%s</h2>'
           % (p2, "Weiterlesen" if edition == "de" else "Read on"),
           '%s    <span class="cf-section-header__count">%s</span>'
           % (p2, MORE[edition] % (len(others), total)),
           "%s  </div>" % p2,
           '%s  <div class="subdivide subdivide--even" style="--subdivide-count:%d">'
           % (p2, len(others)),
           '%s    <div class="cf-blog-grid subdivide__row">' % p2]
    for p in others:
        title = p["titel"] if edition == "de" else p["title"]
        date = news.german(p["datum"]) if edition == "de" else news.en_meta(p["datum"])
        line = date + (" · %s min" % p["minuten"] if p.get("minuten") else "")
        out += ['%s      <div class="cf-blog-col subdivide__col cf-blog-col--1">' % p2,
                '%s        <a class="cf-blog-card cf-blog-card--lead" href="%s">'
                % (p2, news.page_name(p)),
                '%s          <span class="cf-blog-card__title">%s</span>' % (p2, esc(title)),
                '%s          <span class="cf-blog-card__meta">%s</span>' % (p2, esc(line)),
                "%s        </a>" % p2,
                "%s      </div>" % p2]
    out += ["%s    </div>" % p2, "%s  </div>" % p2, "%s</div>" % p2, "%s</section>" % pad]
    return "\n".join(out)


# --------------------------------------------------------------------------

def page(template, post, posts, edition, total, name):
    """One edition of one post: the specimen with nine regions replaced."""
    bs = post["text_de"] if edition == "de" else post["text_en"]
    where = ("design-system/patterns/%s" if edition == "de"
             else "design-system/patterns/en/%s") % SPECIMEN
    more = related(post, posts, edition, total, "    ")
    doc = template
    for region, body in (
            ("head", lambda pad: head(post, edition, pad)),
            ("crumb", lambda pad: crumb(post, edition, pad)),
            ("title", lambda pad: "%s<h1 class=\"cf-page-header__title\">%s</h1>"
                                  % (pad, esc(post["titel" if edition == "de" else "title"]))),
            ("meta", lambda pad: meta_line(post, edition, pad)),
            ("rail", lambda pad: rail(bs, edition, pad)),
            ("byline", lambda pad: byline(post, pad)),
            ("prose", lambda pad: prose(bs, edition, pad)),
            ("tail", lambda pad: tags(post, edition, pad)),
            ("related", lambda pad: related(post, posts, edition, total, pad))):
        doc = splice(doc, region, body, where)

    # THE FOOTER FOLLOWS THE LAST SECTION, in both directions.
    # `cf-footer--detached` is the footer's own gap, and it exists because the
    # section above it is `--flush` and brings none. The first article published
    # has no siblings to read on to, so Weiterlesen is not drawn, and the last
    # thing above the footer is the article body — which brings its own gap.
    # Left detached over it the air doubles, which is the finding
    # scripts/check-footer-parity.py raises as DETACHED and which was drawn
    # exactly that way before this. It comes back the moment a second post is
    # published, without anything here changing.
    if not more:
        doc, n = re.subn(r'(<footer class="cf-footer) cf-footer--detached"', r'\1"', doc)
        if n != 1:
            fail("%s: expected one detached footer to un-detach, found %d" % (name, n))

    # AN EMPTY BYLINE IS NOT AN EMPTY BOX. `.cf-article__byline` carries a
    # bottom rule and the air under it; with no author inside, what is drawn is
    # a hairline hanging over the text with nothing above it — read off the
    # rendered page, where it looks like a rule somebody meant. The whole box
    # goes, and the prose keeps the section's own spacing.
    if not byline(post, ""):
        doc, n = re.subn(
            r"[ \t]*<div class=\"cf-article__byline\">\s*"
            + re.escape(FENCE % "byline") + r"\s*"
            + re.escape(FENCE_END % "byline") + r"\s*</div>\n", "", doc)
        if n != 1:
            fail("%s: expected one empty byline box to remove, found %d" % (name, n))

    # THE SPECIMEN'S OWN NAME, everywhere it points at itself: the two
    # hreflang alternates, the language switch in the nav, and — on the English
    # page — the `../` back to the German edition. Replaced as a string rather
    # than matched attribute by attribute, because every one of them is the
    # same filename and a page that keeps one of them points a crawler at a
    # different article than the one it is on.
    doc = doc.replace(SPECIMEN, name)

    # The banner. On the English side there is one already — build-i18n.py's,
    # naming the specimen as the source — and it is replaced rather than added
    # to: two GENERATED notices disagreeing about what generated the file is
    # worse than none.
    if not doc.startswith(DOCTYPE):
        fail("%s does not begin with a doctype" % where)
        return
    rest = doc[len(DOCTYPE):]
    if rest.lstrip().startswith("<!-- GENERATED"):
        rest = rest[rest.index("-->") + 4:]
    return DOCTYPE + BANNER % (SPECIMEN, post["file"]) + rest


def build():
    """Both editions of every post that has a page. Returns {path: text}."""
    news = store()
    posts = news.read_posts()
    for p in posts:
        p["_news"] = news
    total = len(posts)

    named = {}
    for p in posts:
        name = news.page_name(p)
        if not name:
            continue
        if name in named:
            fail("two posts write the same page, %s — %s and %s. Two headlines "
                 "that reduce to the same name do this; change one of them."
                 % (name, named[name]["file"], p["file"]))
        named[name] = p

    out = {}
    for edition, home in (("de", PATTERNS), ("en", EN)):
        src = home / SPECIMEN
        if not src.exists():
            fail("no %s to build from.%s" % (src.relative_to(ROOT),
                 " Run python3 scripts/build-i18n.py first — the English "
                 "specimen is generated." if edition == "en" else ""))
        template = src.read_text(encoding="utf-8")
        for name, p in named.items():
            out[home / name] = page(template, p, posts, edition, total, name)
    return out


def owned():
    """Every article page on disk, in both editions."""
    return sorted(list(PATTERNS.glob("beitrag-*.html")) + list(EN.glob("beitrag-*.html")))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if a page is stale, missing or orphaned")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    pages = build()
    stale, missing, wrote = [], [], []
    for path, text in sorted(pages.items()):
        rel = path.relative_to(PATTERNS)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            if args.verbose:
                print("  ok       %s" % rel)
            continue
        if args.check:
            (missing if current is None else stale).append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            wrote.append(rel)

    # A PAGE WHOSE POST IS GONE. Unpublishing in Notion removes the file from
    # content/news/, and the page has to go with it or the archive stops
    # listing an article the site still serves at its own address.
    orphans = [p for p in owned() if p not in pages]
    for p in orphans:
        if args.check:
            print("  ORPHAN    %s — no post in content/news/ writes it"
                  % p.relative_to(PATTERNS), file=sys.stderr)
        else:
            p.unlink()

    if args.check:
        if stale or missing or orphans:
            for r in missing:
                print("  MISSING   %s" % r, file=sys.stderr)
            for r in stale:
                print("  STALE     %s" % r, file=sys.stderr)
            print("\n%d article page(s) do not match content/news/.\n"
                  "    run: python3 scripts/build-articles.py"
                  % (len(stale) + len(missing) + len(orphans)), file=sys.stderr)
            return 1
        print("articles OK — %d page(s), %d post(s) with text"
              % (len(pages), len(pages) // 2))
        return 0

    for r in wrote:
        print("  written  %s" % r)
    for p in orphans:
        print("  removed  %s" % p.relative_to(PATTERNS))
    print("articles built — %d page(s) over both editions, %d changed"
          % (len(pages), len(wrote) + len(orphans)))
    if wrote or orphans:
        print("     then: python3 scripts/build-site.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
