#!/usr/bin/env python3
"""One job page per opening, generated from content/jobs/ and the specimen.

THE SAME ARGUMENT AS scripts/build-articles.py, one register over. A vacancy
that has an advertisement behind it needs a page for it, and until now there
was exactly one — karriere-stelle.html, hand-written for the Data Engineer —
while the other three entries in the register linked to their own row because
there was nothing to link to. Writing the fourth ad meant copying six hundred
lines of page and editing the parts that differ, in German, and then again in
English.

SO AN OPENING WITH TEXT IS A PAGE. content/jobs/ holds one file per opening;
one that carries its advertisement carries it in both languages, divided by a
line; and this script writes `stelle-<name>.html` for each of them, in German
beside the patterns and in English under patterns/en/. build-jobs.py links the
register entry to the page it knows this script will write — page_name() is
defined once, there, and read here.

AN OPENING WITHOUT TEXT GETS NO PAGE, and its entry links to its own row on the
register. That is not a placeholder this script invented: karriere.html shipped
exactly that for three of its four entries, with its own note that a link to a
page which does not exist is the thing that must not ship.

THE FURNITURE IS NOT COPIED, IT IS READ. karriere-stelle.html stays hand-written
and is the specimen of the surface: the ten regions fenced by `stelle:…`
comments are the parts that belong to one particular opening, and everything
outside them — the head, the consent banner, the navigation, the two-column
grid, the application section, the footer — is shared by construction. The
English page is the same splice on en/karriere-stelle.html, which
scripts/build-i18n.py has already translated; HTML comments are the one thing
it never touches, so the fences survive into it.

AND THE STRUCTURED DATA IS GENERATED WITH THE PAGE. The JobPosting block is
what a search engine reads instead of the page, and the two disagreeing is the
failure nobody sees: the title, the identifier, the dates, the employment type
and the salary all come from the same fields the visible page is drawn from.
scripts/check-job-posting.py holds them to each other afterwards.

    python3 scripts/build-stellen.py           # write the job pages
    python3 scripts/build-stellen.py --check   # fail if any is stale or orphaned
    python3 scripts/build-stellen.py -v        # name every page

stdlib only, no build step, no dependency. Same python3 that serves the pages.
"""

import argparse
import importlib.util
import json
import os
import pathlib
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import og_meta                                                    # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
PATTERNS = ROOT / "design-system" / "patterns"
EN = PATTERNS / "en"
SPECIMEN = "karriere-stelle.html"

BANNER = (
    "<!-- GENERATED — DO NOT EDIT THIS FILE.\n"
    "     One opening of the register, on the surface of\n"
    "     design-system/patterns/%s. The advertisement is\n"
    "     content/jobs/%s; everything around it is that page.\n"
    "     Change the opening or the specimen, then run:\n"
    "\n"
    "         python3 scripts/build-stellen.py\n"
    "\n"
    "     CI runs `--check`, so an edit made here is lost rather than shipped. -->\n"
)

DOCTYPE = "<!DOCTYPE html>\n"

# The words this script writes that are not in a job file, in the two editions.
# Everything else a reader sees comes from the file, in both languages, which
# is why no string of an advertisement ever enters design-system/i18n/en.json.
WORDS = {
    "de": {"posted": "Ausgeschrieben am", "contact": "Fragen vorab",
           "pay": "Vergütung", "deadline": "Bewerbungsschluss",
           "more": "Weitere offene %s", "one": "Stelle", "many": "Stellen",
           "all": "Alle %d %s mit den vollständigen Rahmenbedingungen stehen auf der",
           "page": "Karriereseite",
           "id": "Die Kennung <strong>%s</strong> steht im Betreff, damit Ihre "
                 "Bewerbung im richtigen Verfahren landet. Sie steht auch in der "
                 "Ausschreibung selbst und ist die einzige Nummer, die wir dafür führen.",
           "desc": "Offene Stelle bei der Control-F GmbH in Konstanz: %s, %s, %s. "
                   "Aufgabe, Anforderungen und Rahmenbedingungen."},
    "en": {"posted": "Posted on", "contact": "Questions first",
           "pay": "Pay", "deadline": "Closing date",
           "more": "More open %s", "one": "position", "many": "positions",
           "all": "All %d %s with their full terms are on the",
           "page": "careers page",
           "id": "Quote <strong>%s</strong> in the subject line so your "
                 "application lands in the right process. It is in the "
                 "advertisement itself and is the only number we keep for it.",
           "desc": "Open position at Control-F GmbH in Konstanz: %s, %s, %s. "
                   "The work, what it takes, and the terms."},
}

MONTHS = ("Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")


def fail(msg):
    print("build-stellen: " + msg, file=sys.stderr)
    sys.exit(1)


def load(name):
    spec = importlib.util.spec_from_file_location(
        "cf_" + name.replace("-", "_"),
        pathlib.Path(__file__).with_name(name + ".py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


JOBS = load("build-jobs")
ART = load("build-articles")           # splice, wrap, inline, anchor, esc

esc = ART.esc
inline = ART.inline
wrap = ART.wrap


def splice(html, name, body, where):
    """Replace one fenced region, keeping the fences and their indentation."""
    start, end = "<!-- stelle:%s -->" % name, "<!-- /stelle:%s -->" % name
    m = re.search(re.escape(start) + r".*?" + re.escape(end), html, re.S)
    if not m:
        fail("%s has no %s … %s region. The fences are how this script knows "
             "what belongs to the opening and what belongs to the page."
             % (where, start, end))
    pad = re.match(r"[ \t]*", html[html.rfind("\n", 0, m.start()) + 1:m.start()]).group(0)
    text = body(pad) if callable(body) else body
    inner = "\n%s\n%s" % (text, pad) if text else "\n%s" % pad
    return html[:m.start()] + start + inner + end + html[m.end():]


def date(iso, edition):
    y, m, d = iso.split("-")
    return "%s.%s.%s" % (d, m, y) if edition == "de" else "%s %s %s" % (d, MONTHS[int(m) - 1], y)


def field(job, edition, de, en):
    return job[de] if edition == "de" else job[en]


# --------------------------------------------------------------------------
# the regions

def head(job, edition, pad):
    title = JOBS.plain_title(job, edition)
    w = WORDS[edition]
    desc = w["desc"] % (title, field(job, edition, "anstellung", "employment"),
                        field(job, edition, "umfang", "hours"))
    shown = "%s — %s — Control-F" % (esc(title),
                                     "Karriere" if edition == "de" else "Careers")
    quoted = esc(desc).replace('"', "&quot;")
    # THE SHARE CARD IS IN THIS REGION for the same reason the title is: og:title
    # and og:description are the page's own two strings said again, and on an
    # opening's page both of them are the opening's. A position is the single
    # most-pasted kind of link this site has, and outside the fence every one of
    # them would unfurl as the Data Engineer specimen.
    #
    # THE PLATE IS /karriere/<rolle>'s, ONE FOR ALL OF THEM. Seeding it on the
    # slug would give every opening its own mark and the generator already takes
    # any seed; what stops it today is that the openings come out of Notion and
    # a plate has to exist before a crawler asks for it. → foundations/share.html
    return "\n".join(pad + line for line in (
        ["<title>%s</title>" % shown,
         '<meta name="description" content="%s">' % quoted]
        + og_meta.block(shown, quoted, "karriere-stelle", edition)))


def ld(job, edition, pad):
    """The JobPosting block, from the same fields the page is drawn from.

    Written here rather than translated, because scripts/build-i18n.py never
    sees this page — and because a structured-data block that says one thing
    while the page says another is the one error a reader cannot see and a
    search engine acts on.
    """
    body = job["de"] if edition == "de" else job["en"]
    data = {
        "@context": "https://schema.org",
        "@type": "JobPosting",
        "title": JOBS.plain_title(job, edition),
        "description": "<p>%s</p>" % esc(body[0][1]),
        "identifier": {"@type": "PropertyValue", "name": "Control-F GmbH",
                       "value": job["kennung"]},
        "datePosted": job["seit"],
    }
    if job.get("frist"):
        data["validThrough"] = job["frist"]
    if job.get("art"):
        data["employmentType"] = [a.strip() for a in job["art"].split(",") if a.strip()]
    data["hiringOrganization"] = {
        "@type": "Organization", "name": "Control-F GmbH",
        "sameAs": "https://www.control-f.de",
        "logo": "https://www.control-f.de/assets/img/logo/cf-logo-horizontal-white.svg"}
    data["jobLocation"] = {
        "@type": "Place",
        "address": {"@type": "PostalAddress", "streetAddress": "Am Seerhein 6",
                    "postalCode": "78467", "addressLocality": "Konstanz",
                    "addressRegion": "BW", "addressCountry": "DE"}}
    if job.get("gehalt_von") and job.get("gehalt_bis"):
        data["baseSalary"] = {
            "@type": "MonetaryAmount", "currency": "EUR",
            "value": {"@type": "QuantitativeValue",
                      "minValue": int(job["gehalt_von"]),
                      "maxValue": int(job["gehalt_bis"]),
                      "unitText": "YEAR"}}
    text = json.dumps(data, ensure_ascii=False, indent=2)
    return "%s<script type=\"application/ld+json\">\n%s\n%s</script>" % (pad, text, pad)


def meta(job, edition, pad):
    w = WORDS[edition]
    return ('%s<span>%s · %s</span>\n'
            '%s<span>%s <time datetime="%s">%s</time></span>'
            % (pad, esc(field(job, edition, "bereich", "area")),
               esc(field(job, edition, "standort", "location")),
               pad, w["posted"], job["seit"], date(job["seit"], edition)))


def task(job, edition, pad):
    """The opening paragraphs of the advertisement — everything before the
    first heading. The rest of the body is the two lists under Ihre Arbeit."""
    body = job["de"] if edition == "de" else job["en"]
    out = []
    for kind, payload in body:
        if kind != "p":
            break
        out.append(wrap(pad, '<p class="measure">', inline(payload, edition), "</p>"))
    return "\n".join(out)


def facts(job, edition, pad):
    """The Eckdaten list: the register's four, then the two the register is
    forbidden to carry — components/vacancy.html: "That is content for the job
    page." — then where to ask."""
    w = WORDS[edition]
    rows = [(term if edition == "de" else en_term,
             field(job, edition, de, en))
            for (term, de, en), en_term in
            zip(JOBS.FACTS, ("Location", "Contract", "Hours", "Start"))]
    # The long form of the address, when the opening carries one: the register
    # needs a label ("Konstanz, hybrid") and this page has room for a sentence.
    if job.get("adresse"):
        rows[0] = (rows[0][0], field(job, edition, "adresse", "address"))
    if job.get("verguetung"):
        rows.append((w["pay"], field(job, edition, "verguetung", "salary")))
    if job.get("frist"):
        rows.append((w["deadline"],
                     '<time datetime="%s">%s</time>' % (job["frist"],
                                                        date(job["frist"], edition))))
    rows.append((w["contact"], '<a href="mailto:info@control-f.io">info@control-f.io</a>'))
    out = []
    for term, value in rows:
        out.append('%s<div class="cf-contact__row">' % pad)
        out.append('%s  <dt class="cf-contact__term">%s</dt>' % (pad, esc(term)))
        out.append('%s  <dd class="cf-contact__value">%s</dd>'
                   % (pad, value if value.startswith("<") else inline(value, edition)))
        out.append("%s</div>" % pad)
    return "\n".join(out)


def prose(job, edition, pad):
    """Everything from the first heading on: `## X` and its list."""
    body = job["de"] if edition == "de" else job["en"]
    out, started = [], False
    for kind, payload in body:
        if kind in ("h2", "h3"):
            started = True
            out.append('%s<h3 id="%s">%s</h3>' % (pad, ART.anchor(payload), inline(payload, edition)))
        elif not started:
            continue
        elif kind in ("ul", "ol"):
            tag = "ul" if kind == "ul" else "ol"
            out.append("%s<%s>" % (pad, tag))
            for item in payload:
                out.append("%s  <li>%s</li>" % (pad, inline(item, edition)))
            out.append("%s</%s>" % (pad, tag))
        elif kind == "p":
            out.append(wrap(pad, "<p>", inline(payload, edition), "</p>"))
        elif kind == "img":
            out.append(ART.picture(payload[0], payload[1], edition, pad))
    return "\n".join(out)


def kennung(job, edition, pad):
    return wrap(pad, '<p class="t-body-sm t-secondary measure">',
                WORDS[edition]["id"] % esc(job["kennung"]), "</p>")


def more(job, jobs, edition, pad):
    """The other openings, as the same register component one row shorter."""
    others = [j for j in jobs if j["slug"] != job["slug"]]
    if not others:
        return ""
    w = WORDS[edition]
    unit = w["one"] if len(others) == 1 else w["many"]
    p2, p4 = pad + "  ", pad + "    "
    out = ['%s<section class="section" aria-labelledby="weitere">' % pad,
           '%s<div class="container">' % p2,
           '%s  <div class="cf-section-header cf-section-header--flush">' % p2,
           '%s    <h2 class="cf-section-header__label" id="weitere">%s</h2>'
           % (p2, esc(w["more"] % unit)),
           '%s    <span class="cf-section-header__count" aria-hidden="true">05</span>' % p2,
           "%s  </div>" % p2,
           '%s  <ul class="cf-vacancies" role="list">' % p2]
    for j in others:
        href = JOBS.page_name(j) or ("karriere.html#" + JOBS.anchor(j))
        out.append('%s<li class="cf-vacancy">' % p4)
        out.append('%s  <p class="cf-vacancy__meta"><span>%s</span></p>'
                   % (p4, esc(field(j, edition, "bereich", "area"))))
        out.append('%s  <h3 class="cf-vacancy__title">' % p4)
        out.append('%s    <a class="cf-vacancy__link" href="%s">%s</a>'
                   % (p4, href, JOBS.title_html(j, edition)))
        out.append("%s  </h3>" % p4)
        out.append(wrap(p4, '<p class="cf-vacancy__excerpt">',
                        esc(field(j, edition, "anriss", "excerpt")), "</p>"))
        out.append('%s  <dl class="cf-vacancy__facts">' % p4)
        for (term, de, en), en_term in zip(JOBS.FACTS,
                                           ("Location", "Contract", "Hours", "Start")):
            out.append('%s    <div class="cf-vacancy__fact">' % p4)
            out.append('%s      <dt class="cf-vacancy__term">%s</dt>'
                       % (p4, esc(term if edition == "de" else en_term)))
            out.append('%s      <dd class="cf-vacancy__value">%s</dd>'
                       % (p4, esc(field(j, edition, de, en))))
            out.append("%s    </div>" % p4)
        out.append("%s  </dl>" % p4)
        out.append("%s</li>" % p4)
    out += ["%s  </ul>" % p2, ""]
    # The count in the closing sentence is the register's length and not this
    # list's: it points at the page where all of them are.
    total = len(jobs)
    out += [wrap(p2 + "  ", '<p class="t-body-sm t-secondary measure after-register">',
                 "%s <a href=\"karriere.html\">%s</a>." % (
                     esc(w["all"] % (total, w["one"] if total == 1 else w["many"])),
                     esc(w["page"])), "</p>"),
            "%s</div>" % p2, "%s</section>" % pad]
    return "\n".join(out)


# --------------------------------------------------------------------------

def page(template, job, jobs, edition, name):
    where = ("design-system/patterns/%s" if edition == "de"
             else "design-system/patterns/en/%s") % SPECIMEN
    doc = template
    for region, body in (
            ("head", lambda pad: head(job, edition, pad)),
            ("ld", lambda pad: ld(job, edition, pad)),
            ("crumb", lambda pad: '%s<span class="cf-breadcrumb__current" '
                                  'aria-current="page">%s</span>'
                                  % (pad, JOBS.title_html(job, edition))),
            ("title", lambda pad: '%s<h1 class="cf-page-header__title">%s</h1>'
                                  % (pad, JOBS.title_html(job, edition))),
            ("meta", lambda pad: meta(job, edition, pad)),
            ("task", lambda pad: task(job, edition, pad)),
            ("facts", lambda pad: facts(job, edition, pad)),
            ("prose", lambda pad: prose(job, edition, pad)),
            ("kennung", lambda pad: kennung(job, edition, pad)),
            ("more", lambda pad: more(job, jobs, edition, pad))):
        doc = splice(doc, region, body, where)

    doc = doc.replace(SPECIMEN, name)
    if not doc.startswith(DOCTYPE):
        fail("%s does not begin with a doctype" % where)
    rest = doc[len(DOCTYPE):]
    if rest.lstrip().startswith("<!-- GENERATED"):
        rest = rest[rest.index("-->") + 4:]
    return DOCTYPE + BANNER % (SPECIMEN, job["file"]) + rest


def build():
    jobs = JOBS.read_jobs()
    named = {}
    for j in jobs:
        name = JOBS.page_name(j)
        if name:
            named[name] = j
    out = {}
    for edition, home in (("de", PATTERNS), ("en", EN)):
        src = home / SPECIMEN
        if not src.exists():
            fail("no %s to build from.%s" % (src.relative_to(ROOT),
                 " Run python3 scripts/build-i18n.py first — the English "
                 "specimen is generated." if edition == "en" else ""))
        template = src.read_text(encoding="utf-8")
        for name, j in named.items():
            out[home / name] = page(template, j, jobs, edition, name)
    return out


def owned():
    return sorted(list(PATTERNS.glob("stelle-*.html")) + list(EN.glob("stelle-*.html")))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    pages = build()
    stale, missing, wrote = [], [], []
    for path, text in sorted(pages.items()):
        rel = path.relative_to(PATTERNS)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            if args.verbose:
                print("  ok       %s" % rel)
            continue
        if args.check:
            (missing if current is None else stale).append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            wrote.append(rel)

    # A page whose opening is gone. A filled position leaves content/jobs/, and
    # its page has to go with it — an advertisement the register stopped
    # listing and the site still serves is the worst of the three states.
    orphans = [p for p in owned() if p not in pages]
    for p in orphans:
        if args.check:
            print("  ORPHAN    %s — no opening in content/jobs/ writes it"
                  % p.relative_to(PATTERNS), file=sys.stderr)
        else:
            p.unlink()

    if args.check:
        if stale or missing or orphans:
            for r in missing:
                print("  MISSING   %s" % r, file=sys.stderr)
            for r in stale:
                print("  STALE     %s" % r, file=sys.stderr)
            print("\n%d job page(s) do not match content/jobs/.\n"
                  "    run: python3 scripts/build-stellen.py"
                  % (len(stale) + len(missing) + len(orphans)), file=sys.stderr)
            return 1
        print("stellen OK — %d page(s), %d opening(s) with an ad"
              % (len(pages), len(pages) // 2))
        return 0

    for r in wrote:
        print("  written  %s" % r)
    for p in orphans:
        print("  removed  %s" % p.relative_to(PATTERNS))
    print("stellen built — %d page(s) over both editions, %d changed"
          % (len(pages), len(wrote) + len(orphans)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
