#!/usr/bin/env python3
"""Fail a `--tile` set on markup that never joined the recipe that reads it.

`--tile` IS READ IN EXACTLY ONE DECLARATION IN THE WHOLE SYSTEM. base.css
writes

    .tiles {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(min(var(--tile, 16rem), 100%), 1fr));
      gap: var(--flow, var(--space-4));
    }

and nothing else in any stylesheet looks at the property. So a rule that sets
`--tile` is not styling anything — it is CONFIGURING `.tiles`, and it does that
only for elements that carry `.tiles`. Set it on an element without the class
and every term of it is inert: the custom property inherits down the tree
perfectly, computes to the value the author wrote, shows that value in
devtools, and lays nothing out. The element stays block flow.

WHAT THAT LOOKS LIKE ON A PAGE is not an error. It is the same content in
source order with the grid's gap missing, which is the one difference a
reader's eye is least likely to name and most likely to feel. patterns/
expertise.html shipped four of them — every `.cf-info-card__facts` on the
page, one per field:

    <div class="cf-info-card__facts">          <!-- no .tiles -->

against components.css, which sets the two numbers and says in the comment
above them what markup they need:

    /* .tiles carries the recipe; this only sets the two numbers that are its
       own. Needs the guard .tiles adds — a fact column with a 13rem floor
       overflows a narrow phone otherwise. Markup:
       class="cf-info-card__facts tiles tiles--fit". */
    .cf-info-card__facts {
      margin-top: var(--space-8);
      --tile: 13rem;
      --flow: var(--space-6);
    }

Measured on the shipping page at nine viewports, in both motion preferences,
the computed style of that div read `display: block`, `grid-template-columns:
none`, `gap: normal` — and `--tile: 13rem`, `--flow: 1.5rem`, both present and
both dead. The two fact columns stacked with no gap between them at every
width, so the second group's label sat **0 px** below the chips of the first
while sitting **12 px** above its own. A label twice as close to the group it
does not belong to as to the group it does. That is what got reported, in
those words: "vor 2. Überschrift zu wenig Abstand".

THE GUARD IS THE HALF THAT BITES LATER. `.tiles` is not only the grid; it is
`min(var(--tile), 100%)` and `min-width: 0` on the children, and base.css's own
header says why that is a class and not a convention:

    That guard is why this is a class and not a convention. It is one term, it
    is easy to leave out, and leaving it out is invisible until somebody opens
    the page at a width nobody tested.

A 13rem floor is 208 px. The fact column is 214 px wide at a 320 px viewport,
and narrower than the floor for any reader who has enlarged their root font.
Adding the class without the guard would have traded a missing gap for a
sideways scroll on a phone — which is why the fix is the whole recipe and not
a hand-written `display: grid`.

WHAT IS CHECKED. Every rule, in every stylesheet that ships and every
page-local <style> block, whose body declares `--tile`. The selector's subject
— the last compound, so `.a .b` is about `.b` — has to be a single class, and
then every element in the tree carrying that class has to carry `tiles` too.
Run against the tree the day it was written: nineteen classes configure the
recipe, forty elements carry one of them, and all forty join it.

  the subject only     `.a .b { --tile: … }` configures `.b`. A compound
                       subject (`.a.b`) is skipped rather than guessed at, and
                       counted in -v: which of the two classes the markup is
                       keyed on is not decidable from the stylesheet, and a
                       check that guessed would fail a page for the wrong
                       class name.

  `--flow` is not      It is read by `.stack`, `.cluster` AND `.tiles`, and it
  checked              inherits on purpose — foundations/layout.html sets it on
                       a wrapper for the stack inside it, which is legal and
                       used. `--tile` is read on the element that carries the
                       class and nowhere else, so it is the one of the pair
                       that can be decided from the markup alone.

  the root pages       are scanned as well as the sources under design-system/.
                       They are generated by build-site.py and so a fault shows
                       up twice, which is honest: the root page is what
                       deploys. build-site.py --check is what keeps the pair in
                       step; this says nothing about that.

  prototypes/          is declared not-yet-system by the README and is out of
                       this check's scope as it is out of the others'.

Proven failing on a reintroduction: `tiles tiles--fit` removed from one of the
four divs in patterns/expertise.html is caught in both the pattern and the
generated root page, by class name and line.

    python3 scripts/check-tile-recipe.py       # check, exit 1 on a finding
    python3 scripts/check-tile-recipe.py -v    # list every configuring rule,
                                               # every element that joins the
                                               # recipe, and every selector
                                               # skipped for a compound subject
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DS = ROOT / "design-system"

# prototypes/ is not-yet-system, the same exclusion every other check makes.
EXCLUDED_DIRS = ("prototypes",)

# The class that reads --tile. One name, because there is one rule.
RECIPE = "tiles"

COMMENT = re.compile(r"/\*.*?\*/", re.S)
# A rule is a run with no braces in it, taken up to its own closing brace. The
# selector may not contain @, which drops the at-rule preludes; a rule NESTED
# inside @media still matches, because the text between the media block's brace
# and the inner selector is whitespace.
RULE = re.compile(r"([^{}@]+?)\{([^{}]*?)\}", re.S)
# `--tile:` and not `var(--tile, …)` — the reference in base.css's own
# grid-template-columns has a comma after the name, never a colon.
SETS_TILE = re.compile(r"(?:^|;|\s)--tile\s*:")
STYLE_BLOCK = re.compile(r"<style[^>]*>(.*?)</style>", re.S)
# Any start tag carrying a class attribute. Attribute values in this tree are
# double-quoted throughout; check-quoted-attrs.py is what keeps that true.
TAG = re.compile(r"<[a-zA-Z][^>]*\sclass=\"([^\"]*)\"")
BARE_CLASS = re.compile(r"\.([A-Za-z0-9_-]+)")


def subject(selector):
    """The class a selector is about, or None if that is not decidable.

    The subject of a compound selector is its last compound — `.a .b`, `.a > .b`
    and `.a + .b` all style `.b`. Pseudo-classes and pseudo-elements are
    dropped: `.b:hover` and `.b::before` are still about `.b`.
    """
    sel = selector.strip()
    if not sel:
        return None
    # Combinators to spaces, then take the last token.
    sel = re.sub(r"[>+~]", " ", sel)
    last = sel.split()[-1]
    # Drop pseudo-classes/elements, including a functional one's argument.
    last = re.sub(r"::?[A-Za-z-]+(\([^)]*\))?", "", last)
    m = BARE_CLASS.fullmatch(last)
    return m.group(1) if m else None


def configuring_classes(css, origin, skipped):
    """Class names whose rules set --tile, read out of one stylesheet."""
    found = {}
    for sel, body in RULE.findall(COMMENT.sub("", css)):
        if not SETS_TILE.search(body):
            continue
        for part in sel.split(","):
            name = subject(part)
            if name is None:
                if part.strip():
                    skipped.append((origin, part.strip()))
                continue
            found.setdefault(name, origin)
    return found


def html_files():
    for path in sorted(DS.rglob("*.html")):
        if any(part in EXCLUDED_DIRS for part in path.relative_to(DS).parts):
            continue
        yield path
    yield from sorted(ROOT.glob("*.html"))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    skipped = []
    classes = {}
    for sheet in sorted((DS / "assets" / "css").glob("*.css")):
        classes.update(
            configuring_classes(sheet.read_text(encoding="utf-8"),
                                sheet.relative_to(ROOT), skipped)
        )
    # Page-local <style> blocks configure the recipe as often as the sheets do:
    # every foundations page sets its own tile minimum for its own gallery.
    for path in html_files():
        text = path.read_text(encoding="utf-8")
        for block in STYLE_BLOCK.findall(text):
            for name, origin in configuring_classes(
                block, path.relative_to(ROOT), skipped
            ).items():
                classes.setdefault(name, origin)

    if not classes:
        print("check-tile-recipe: no rule sets --tile — nothing to hold", file=sys.stderr)
        return 1

    findings, joined = [], []
    for path in html_files():
        rel = path.relative_to(ROOT)
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            for value in TAG.findall(line):
                names = set(value.split())
                configured = sorted(names & set(classes))
                if not configured:
                    continue
                if RECIPE in names:
                    joined.append((rel, lineno, configured))
                else:
                    findings.append((rel, lineno, configured, value))

    if args.verbose:
        print(f"{len(classes)} classes configure the recipe:")
        for name, origin in sorted(classes.items()):
            print(f"  --tile on .{name:24} {origin}")
        for rel, lineno, configured in joined:
            print(f"  joins  {rel}:{lineno}  .{' .'.join(configured)}")
        for origin, sel in skipped:
            print(f"  skipped (compound subject)  {origin}  {sel}")
        print()

    if findings:
        print("--tile set on an element that never joined the recipe that reads it.")
        print("`.tiles` is the only rule in the system that looks at --tile; without")
        print("the class the property inherits, computes, and lays nothing out.\n")
        for rel, lineno, configured, value in findings:
            print(f"  {rel}:{lineno}")
            print(f"    .{' .'.join(configured)} configures --tile, and the element is")
            print(f"    class=\"{value}\"")
            print(f"    add: tiles  (and tiles--fit if the survivors should stretch)\n")
        print(f"{len(findings)} element(s) configure the tile recipe without joining it.")
        return 1

    print(
        f"tile recipe OK — {len(classes)} classes configure --tile, "
        f"{len(joined)} elements carry one, every one of them on .{RECIPE}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
