#!/usr/bin/env python3
"""A root has no free ends.

The twenty-ninth check, and the one whose failure a screenshot showed all along
without anybody reading it as a failure. The statement-to-process illustration
on patterns/landing-page.html carries the reader from "Tausende Sensoren
erzeugen Daten" down into the frame the four process cards are built in. It is
a drawing of data arriving somewhere. A stroke in it that simply stops is the
drawing saying the opposite, quietly, in the one place the page cannot afford
it.

WHAT IT USED TO SAY. Measured on the shipped page at 1440x900, the seven
vertical drops landed within 5 px of the frame's top rail -- and the two runs
they hung off did not. The left run ended 320 px above the rail and the right
run 32 px, each finishing at a node with a stub of a different line after it.
Nothing in the markup recorded which was intended. Both were plausible. That is
exactly the state a check exists for: a fact that is true of some of the
elements, false of others, and invisible in review because 1 px of hairline at
62 % opacity ending in the middle of a wash looks like a drawing decision.

THE RULE. Every endpoint of every segment must ARRIVE:

  * on the rail          -- y is the bottom of the flow's own box, which is
                            where the frame's top edge is; the drawing hands
                            over there
  * at the void          -- the single start point the trunk leaves from, which
                            is the statement's own circle
  * on another segment   -- the endpoint lies on some other segment of the same
                            drawing, whether at its end or partway along it.
                            A T is an arrival. A junction is an arrival.

Nothing else is. A terminal 5 px short of another line is not on it, and the
tolerance here is ZERO: the geometry is generated by
scripts/expertise-objects/gen-flow-root.py in exact rational arithmetic and
pasted, so any near-miss is a hand edit, which is the thing worth catching.

AND THE ANGLES, in the same sweep and for the same reason. foundations/
geometry.html publishes four angles and the neutral 0; a recursive form that
drifts off them stops being this system's drawing and becomes an organic
squiggle it has no vocabulary for. Every segment must be 0, 26.57, 45, 63.43 or
90 degrees -- which in path data means dx/dy of 0, 1/2, 1, 2, or a vertical.

AND THE NODES. foundations/illustration.html: "a node marks a point the
construction actually depends on", and "eight is a lot for one object; twelve
is too many". So every node must sit on a junction -- a point two or more
segments meet at -- and there may be at most twelve.

The check reads the markup, not the generator. The generator asserts the same
things about its own output and cannot see a hand edit made afterwards, which
is where every previous drift in this repository has come from.
"""

import argparse
import math
import re
import sys
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PATTERNS = ROOT / "design-system" / "patterns"
# The statement-to-process chain moved to prototypes/ on 2026-07-28;
# these checks follow the drawing, not the folder.
PROTOTYPES = ROOT / "design-system" / "prototypes"

# class -> (segment class, node class, the y that counts as the rail)
DRAWINGS = {"lp-flow": ("lp-flow__seg", "lp-flow__node")}

SVG_RE = re.compile(r'<svg\b[^>]*class="([^"]*)"[^>]*viewBox="([^"]*)"(.*?)</svg>', re.S)
PATH_RE = re.compile(r'<path\b[^>]*class="([^"]*)"[^>]*\bd="([^"]*)"', re.S)
CIRCLE_RE = re.compile(r'<circle\b[^>]*class="([^"]*)"[^>]*\bcx="([^"]*)"[^>]*\bcy="([^"]*)"', re.S)
CMD_RE = re.compile(r'([MLVH])\s*(-?[\d.]+)(?:[ ,]+(-?[\d.]+))?')

# dx/dy for the four angles that are not vertical. 0 is the level step.
RATIOS = {Fraction(0), Fraction(1, 2), Fraction(1), Fraction(2)}


def rational(text):
    return Fraction(text).limit_denominator(10 ** 6)


def parse_path(d):
    """The five commands this drawing uses, as a list of segments."""
    segs, cur = [], None
    for cmd, a, b in CMD_RE.findall(d):
        if cmd == "M":
            cur = (rational(a), rational(b))
        elif cmd == "L":
            nxt = (rational(a), rational(b))
            segs.append((cur, nxt))
            cur = nxt
        elif cmd == "V":
            nxt = (cur[0], rational(a))
            segs.append((cur, nxt))
            cur = nxt
        elif cmd == "H":
            nxt = (rational(a), cur[1])
            segs.append((cur, nxt))
            cur = nxt
    return segs


def on_segment(p, seg):
    (x1, y1), (x2, y2) = seg
    if p in (seg[0], seg[1]):
        return True
    if (x2 - x1) * (p[1] - y1) - (y2 - y1) * (p[0] - x1) != 0:
        return False
    return min(x1, x2) <= p[0] <= max(x1, x2) and min(y1, y2) <= p[1] <= max(y1, y2)


def angle_of(seg):
    (x1, y1), (x2, y2) = seg
    dx, dy = x2 - x1, y2 - y1
    if dx == 0:
        return "90"
    ratio = abs(Fraction(dx, dy)) if dy else None
    if ratio is None:
        return "0"
    if ratio not in RATIOS:
        return None
    return f"{math.degrees(math.atan2(abs(dy), abs(dx))):.2f}"


def check_drawing(name, cls, body, view_box, verbose):
    seg_cls, node_cls = DRAWINGS[cls]
    rail = rational(view_box.split()[3])

    segs, nodes = [], []
    for classes, d in PATH_RE.findall(body):
        if seg_cls in classes.split():
            segs.extend(parse_path(d))
    for classes, cx, cy in CIRCLE_RE.findall(body):
        if node_cls in classes.split():
            nodes.append((rational(cx), rational(cy)))

    findings = []
    if not segs:
        return [f"{name}: .{cls} carries no .{seg_cls} at all"], 0, 0

    # The void: the one point a segment may start from without another segment
    # under it. It is the topmost start, and there must be exactly one.
    tops = sorted({s[0] for s in segs}, key=lambda p: (p[1], p[0]))
    void = tops[0]

    for i, seg in enumerate(segs):
        angle = angle_of(seg)
        if angle is None:
            (x1, y1), (x2, y2) = seg
            findings.append(
                f"{name}: segment {i} runs M{x1} {y1} L{x2} {y2}, which is "
                f"{math.degrees(math.atan2(abs(y2 - y1), abs(x2 - x1))):.2f}deg — "
                f"off the four angles foundations/geometry.html publishes"
            )
        for end, p in (("start", seg[0]), ("end", seg[1])):
            if p[1] == rail or p == void:
                continue
            if any(on_segment(p, other) for j, other in enumerate(segs) if j != i):
                continue
            findings.append(
                f"{name}: segment {i}'s {end} at ({p[0]}, {p[1]}) arrives at nothing — "
                f"not the rail at y {rail}, not the void at ({void[0]}, {void[1]}), "
                f"and not on any other segment. A root has no free ends."
            )

    junctions = set()
    for i, seg in enumerate(segs):
        for p in seg:
            if any(on_segment(p, o) for j, o in enumerate(segs) if j != i):
                junctions.add(p)
    for p in nodes:
        if p not in junctions:
            findings.append(
                f"{name}: a node stands at ({p[0]}, {p[1]}), which no two segments meet at — "
                f"foundations/illustration.html: a node marks a point the construction depends on"
            )
    # THE CEILING IS AN OBJECT'S, AND .lp-flow IS A GRAPH. The manual's
    # sentence — "eight is a lot for one object; twelve is too many" — is about
    # an isometric object, where a node is a construction point and the reader
    # is counting how a form is built. The root's subject IS data dividing, and
    # check-flow-crossings.py reads a meeting with no dot on it as "not
    # connected", so every one of its eighteen divisions has to carry one.
    # check-flow-nodes.py owns that argument in full; this is the same
    # exemption stated where the second count lives.
    if cls != "lp-flow" and len(nodes) > 12:
        findings.append(
            f"{name}: {len(nodes)} nodes on one object — foundations/illustration.html "
            f"calls eight a lot and twelve too many"
        )

    if verbose:
        on_rail = sum(1 for s in segs if s[1][1] == rail)
        print(f"  {name} .{cls}: {len(segs)} segments, {len(nodes)} nodes, "
              f"{on_rail} terminals on the rail at y {rail}, void at "
              f"({void[0]}, {void[1]})")
        def show(v):
            return str(int(v)) if v.denominator == 1 else f"{float(v):g}"
        for i, seg in enumerate(segs):
            (x1, y1), (x2, y2) = seg
            lands = "the rail" if y2 == rail else "another branch"
            print(f"    {i:>2}  {angle_of(seg):>5}deg  "
                  f"({show(x1):>7}, {show(y1):>5}) -> ({show(x2):>7}, {show(y2):>5})"
                  f"  lands on {lands}")

    return findings, len(segs), len(nodes)


def main():
    parser = argparse.ArgumentParser(description="A root has no free ends.")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="print every segment and what its terminal lands on")
    args = parser.parse_args()

    findings, segs, nodes, drawings = [], 0, 0, 0
    for page in sorted([*PATTERNS.glob("*.html"), *PROTOTYPES.glob("*.html")]):
        text = page.read_text(encoding="utf-8")
        for classes, view_box, body in SVG_RE.findall(text):
            for cls in DRAWINGS:
                if cls in classes.split():
                    drawings += 1
                    f, s, n = check_drawing(page.name, cls, body, view_box, args.verbose)
                    findings += f
                    segs += s
                    nodes += n

    if not drawings:
        print("flow terminals: no drawing to check — the selector went stale")
        return 1
    if findings:
        print(f"\nflow terminals: {len(findings)} finding(s)")
        for f in findings:
            print(f"  {f}")
        return 1
    print(f"flow terminals OK — {segs} segments across {drawings} drawing(s), every terminal "
          f"on the rail, the void or another branch, every segment on a brand angle, "
          f"and {nodes} nodes all on junctions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
