#!/usr/bin/env python3
"""The contact form and the Worker that answers it agree on every name.

The first check that reads something other than HTML and CSS, because the
contact form is the first thing on this site whose behaviour is not entirely
in the page. patterns/kontakt.html is the form; worker/ is the server that
receives it. Between them run nine agreements, none of which any other check
can see, and every one of which breaks silently:

  1. THE FIELD NAMES. Each .cf-field wrapper in the form carries data-field,
     and its value is the name= of the control inside it. The Worker adds
     cf-field--invalid by that attribute — a wrapper without one is a field
     that can never be marked wrong, and the reader gets a summary pointing at
     a field that looks fine.

  2. THE IDS. render.js maps each field to the id of its control. An id that
     moves takes the per-field message, aria-invalid and the refilled value
     with it, and HTMLRewriter reports nothing when a selector matches nothing.

  3. THE TOPICS. validate.js keeps the five <option> labels so that a value
     from outside the list can be dropped. A sixth option added to the form
     would be silently discarded on every submit.

  4. THE HONEYPOT. index.js reads the field the form calls "website". Rename
     it on one side and the trap is a normal field: every bot passes, and no
     one notices, because nothing about the page changes.

  5. THE ANCHOR. render.js inserts the error summary before form[method=post].
     Exactly one such form is on the page. If it stops matching, the response
     to a failed submit is the plain page — correct, but with nothing telling
     the reader what went wrong.

  6. THE MESSAGES. Two of the strings in validate.js are quoted from
     components/forms.html, which is where the design system writes what an
     error sounds like. They are supposed to be the same words.

  7. THE ROUTES. index.js names the paths it answers and the pages it redirects
     to on success. All of them must be files the build actually ships.

  8. THE WORKER'S REACH. A route in index.js that wrangler.toml does not name
     in run_worker_first is a route the Worker never runs for: Cloudflare's
     asset server answers the POST with the page and a 200, the reader sees
     their own form again with no error and no thank-you, and no mail is ever
     sent. Nothing logs it and no page looks different. This is the one
     agreement that is not between the form and the Worker but between the
     Worker and its configuration, and it is checked here because it fails the
     same way as the rest: in silence.

  9. THE EDITIONS. Both of the above run twice, once per language. The English
     pages are generated by build-i18n.py, which changes words and nothing
     else, so the ids, the data-field attributes and the honeypot must come
     through identical — and the topics and the error messages must not. Each
     locale named in index.js's FORMS table needs its own branch in every
     table of validate.js, and the two branches of MESSAGES must offer the same
     keys, or a missing one is a TypeError at submit time.

Every one of these photographs as a working page. That is the same shape as
the checks beside this one.

stdlib only, no build step, no dependency — the JavaScript is read as text,
not parsed. The patterns are the source of truth; the Worker follows them.

    python3 scripts/check-form-contract.py       # check, exit 1 on a finding
    python3 scripts/check-form-contract.py -v    # list every agreement audited
"""

import argparse
import pathlib
import re
import sys
from html.parser import HTMLParser

ROOT = pathlib.Path(__file__).resolve().parent.parent
PATTERNS = ROOT / "design-system" / "patterns"
FORMS_DOC = ROOT / "design-system" / "components" / "forms.html"
WORKER = ROOT / "worker"
WRANGLER = ROOT / "wrangler.toml"

COMMENT = re.compile(r"<!--.*?-->", re.S)

# The two editions of the contact page, and the path each one posts to. The
# English page is generated into patterns/en/ and ships to /en/ at the root;
# both carry the same relative action, so each posts to its own address.
EDITIONS = [
    ("de", PATTERNS / "kontakt.html", "/kontakt.html"),
    ("en", PATTERNS / "en" / "kontakt.html", "/en/kontakt.html"),
]

# The honeypot's name, written once here and asserted on both sides.
HONEYPOT = "website"

# The two strings validate.js quotes from the component page. German only:
# the component pages are the design system's own documentation and are not
# translated, so the English messages have no specimen to be quoted from.
QUOTED = [
    "Bitte geben Sie eine gültige E-Mail-Adresse an.",
    "Bitte schreiben Sie uns, worum es geht.",
]

# The tables in validate.js that must carry a branch for every locale the
# Worker serves.
LOCALE_TABLES = ("TOPICS", "FIELD_LABELS", "MESSAGES", "SEND_FAILED", "RATE_LIMITED",
                 "COUNT_WORDS")


class FormReader(HTMLParser):
    """Pulls the contact form's shape out of the pattern page.

    Only the first <form method="post"> is read — the page has one, and clause
    5 is what keeps it that way.
    """

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.forms = 0
        self.in_form = False
        self.depth = 0
        # data-field value -> {"line": int, "names": [str], "ids": [str]}
        self.wrappers = {}
        self.bare_wrappers = []          # .cf-field without data-field
        self.stack = []                  # open data-field wrappers
        self.names = {}                  # name= -> id=
        self.options = []                # <option> labels, in document order
        self.in_option = False
        self.option_is_prompt = False
        self.option_buf = ""
        self.action = None

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        line = self.getpos()[0]

        if tag == "form" and (a.get("method") or "").lower() == "post":
            self.forms += 1
            if self.forms == 1:
                self.in_form = True
                self.depth = 0
                self.action = a.get("action")
                return

        if not self.in_form:
            return

        self.depth += 1

        classes = (a.get("class") or "").split()
        if "cf-field" in classes:
            field = a.get("data-field")
            if field is None:
                self.bare_wrappers.append(line)
            else:
                self.wrappers[field] = {"line": line, "names": [], "ids": []}
                self.stack.append((field, self.depth))

        if tag in ("input", "select", "textarea"):
            name, ident = a.get("name"), a.get("id")
            if name:
                self.names[name] = ident
            if self.stack and name:
                self.wrappers[self.stack[-1][0]]["names"].append(name)
                self.wrappers[self.stack[-1][0]]["ids"].append(ident)

        if tag == "option":
            self.in_option = True
            self.option_buf = ""
            # The prompt is the option with an explicit empty value —
            # "Bitte wählen" on one edition and "Please choose" on the other.
            # Read off the attribute rather than the words, so this holds for
            # a third edition nobody has written yet.
            self.option_is_prompt = a.get("value") == ""

    def handle_data(self, data):
        if self.in_option:
            self.option_buf += data

    def handle_endtag(self, tag):
        if tag == "option" and self.in_option:
            self.in_option = False
            if not self.option_is_prompt:
                self.options.append(self.option_buf.strip())
            return

        if not self.in_form:
            return

        if tag == "form":
            self.in_form = False
            return

        if self.stack and self.stack[-1][1] == self.depth:
            self.stack.pop()
        self.depth -= 1

    def topics(self):
        return [o for o in self.options if o]


def js_object(text, name):
    """The body of an exported top-level object literal, as text."""
    m = re.search(r"(?:export )?const %s = \{(.*?)\n\};" % re.escape(name), text, re.S)
    return m.group(1) if m else None


def js_branch(text, name, locale):
    """The string literals of one locale's branch of an object of arrays."""
    body = js_object(text, name)
    if body is None:
        return None
    m = re.search(r"\n  %s: \[(.*?)\n  \]," % re.escape(locale), body, re.S)
    if not m:
        return None
    return re.findall(r'"([^"]*)"', m.group(1))


def js_has_branch(text, name, locale):
    """Whether a table names this locale at all, in any shape."""
    body = js_object(text, name)
    if body is None:
        return False
    return re.search(r"\n  %s:" % re.escape(locale), body) is not None


def js_message_keys(text, locale):
    """The message names one locale's branch of MESSAGES defines."""
    body = js_object(text, "MESSAGES")
    if body is None:
        return None
    m = re.search(r"\n  %s: \{(.*?)\n  \}," % re.escape(locale), body, re.S)
    if not m:
        return None
    return set(re.findall(r"\n    (\w+):", m.group(1)))


def js_forms(text):
    """index.js's FORMS table: route -> (locale, thanks path)."""
    body = js_object(text, "FORMS")
    if body is None:
        return None
    out = {}
    for row in re.finditer(
        r'"([^"]+)":\s*\{\s*locale:\s*"(\w+)",\s*thanks:\s*"([^"]+)"', body
    ):
        out[row.group(1)] = (row.group(2), row.group(3))
    return out


def js_fields(text):
    """render.js's FIELDS table: field -> (input selector, wrapper selector)."""
    m = re.search(r"const FIELDS = \{(.*?)\n\};", text, re.S)
    if not m:
        return None
    out = {}
    for row in re.finditer(
        r'(\w+):\s*\{\s*input:\s*"([^"]+)",\s*wrapper:\s*\'([^\']+)\'', m.group(1)
    ):
        out[row.group(1)] = (row.group(2), row.group(3))
    return out


def worker_first():
    """The paths run_worker_first names, read out of wrangler.toml as text."""
    src = WRANGLER.read_text(encoding="utf-8")
    m = re.search(r"^run_worker_first = \[(.*?)\]", src, re.M | re.S)
    if not m:
        return None
    return set(re.findall(r'"([^"]+)"', m.group(1)))


def js_directories(text):
    """index.js's DIRECTORIES set."""
    m = re.search(r"const DIRECTORIES = new Set\(\[(.*?)\]\);", text, re.S)
    if not m:
        return None
    return set(re.findall(r'"([^"]+)"', m.group(1)))


def audit(verbose):
    findings = []
    say = lambda msg: findings.append("  kontakt form: %s" % msg)

    validate_js = (WORKER / "validate.js").read_text(encoding="utf-8")
    render_js = (WORKER / "render.js").read_text(encoding="utf-8")
    index_js = (WORKER / "index.js").read_text(encoding="utf-8")

    # 5. THE ANCHOR, worker side. Read once: one render.js serves both editions.
    if 'rewriter.on("form[method=\'post\']"' not in render_js:
        say("render.js no longer selects form[method='post'] — the error "
            "summary has no anchor")

    fields = js_fields(render_js)
    if fields is None:
        say("render.js has no readable FIELDS table")

    routes = js_forms(index_js)
    if routes is None:
        say("index.js has no readable FORMS table")
        routes = {}

    readers = {}
    origins = {}

    for locale, pattern, route in EDITIONS:
        where = pattern.relative_to(ROOT)
        tell = lambda msg, where=where: findings.append("  %s: %s" % (where, msg))

        if not pattern.exists():
            tell("does not exist — run python3 scripts/build-i18n.py")
            continue

        reader = FormReader()
        reader.feed(COMMENT.sub("", pattern.read_text(encoding="utf-8")))
        readers[locale] = reader

        # 5. THE ANCHOR, page side.
        if reader.forms != 1:
            tell('render.js inserts the summary before form[method="post"], '
                 "which matches %d forms on the page — it must match exactly one"
                 % reader.forms)

        # 1. THE FIELD NAMES.
        for line in reader.bare_wrappers:
            tell("the .cf-field at line %d carries no data-field, so the Worker "
                 "cannot mark it invalid" % line)

        for field, info in sorted(reader.wrappers.items()):
            if len(info["names"]) != 1:
                tell("data-field=%r wraps %d named controls; it must wrap "
                     "exactly one" % (field, len(info["names"])))
                continue
            if info["names"][0] != field:
                tell("data-field=%r at line %d wraps a control named %r — the "
                     "attribute must carry the control's own name"
                     % (field, info["line"], info["names"][0]))

        # 2. THE IDS.
        if fields is not None:
            for field, (selector, wrapper) in sorted(fields.items()):
                info = reader.wrappers.get(field)
                if info is None:
                    tell("render.js knows a field %r that this form does not have"
                         % field)
                    continue
                want = '[data-field="%s"]' % field
                if wrapper != want:
                    tell("render.js selects the %r wrapper as %s, not %s"
                         % (field, wrapper, want))
                ident = info["ids"][0] if info["ids"] else None
                if selector != "#%s" % ident:
                    tell("render.js selects the %r control as %s, but this form "
                         "gives it id=%r" % (field, selector, ident))
            for field in sorted(set(reader.wrappers) - set(fields)):
                tell("this form has a field %r that render.js does not know — it "
                     "can never be marked invalid or refilled" % field)

        # 3. THE TOPICS, against this edition's own list.
        topics = js_branch(validate_js, "TOPICS", locale)
        if topics is None:
            tell("validate.js has no readable TOPICS branch for %r" % locale)
        elif reader.topics() != topics:
            tell("validate.js's %s TOPICS %r do not match this form's options "
                 "%r — a topic outside the list is dropped on every submit"
                 % (locale, topics, reader.topics()))

        # 4. THE HONEYPOT.
        if HONEYPOT not in reader.names:
            tell("no %r field — the honeypot the Worker checks is gone" % HONEYPOT)

        # The form must reach the Worker route for its own edition, carrying
        # the #fehler fragment so the browser lands on the summary without a
        # script. Two shapes are legitimate and the check takes either:
        #
        #   kontakt.html#fehler   posting to its own address, which is right
        #                         once the Worker serves the site itself
        #   https://…/<route>     posting across origins, which is what the
        #                         GitHub Pages arrangement needs, since Pages
        #                         answers a POST with 405
        #
        # What is never right is an absolute address whose path is not this
        # edition's route: an English form pointing at /kontakt.html would be
        # answered in German, with the German topics, and nothing would look
        # wrong until someone read the reply.
        action = reader.action or ""
        if action == "kontakt.html#fehler":
            origins.setdefault("self", []).append(str(where))
        elif action.startswith("https://"):
            origin, _, rest = action[len("https://"):].partition("/")
            origins.setdefault("https://" + origin, []).append(str(where))
            if rest != "%s#fehler" % route.lstrip("/"):
                tell("the form posts to https://%s/%s, but this edition's route "
                     "is %s#fehler — the other edition's Worker would answer it, "
                     "in the other language" % (origin, rest, route.lstrip("/")))
        else:
            tell("the form's action is %r — it must be either its own address "
                 "with the #fehler fragment or an absolute https address ending "
                 "in this edition's route" % reader.action)

        # 9. THE EDITIONS. Every table needs this locale.
        for table in LOCALE_TABLES:
            if not js_has_branch(validate_js, table, locale):
                tell("validate.js's %s has no %r branch — this edition would "
                     "answer in another language, or not at all" % (table, locale))

        # The route this edition posts to must be one the Worker answers.
        if route not in routes:
            tell("posts to %s, which index.js's FORMS table does not name — the "
                 "asset server would answer the POST with a 200 and no mail "
                 "would be sent" % route)

    # 4. THE HONEYPOT, worker side.
    if '"%s"' % HONEYPOT not in index_js:
        say("index.js no longer reads a field named %r" % HONEYPOT)

    # Both editions must post to the SAME place. Half a cutover — one edition
    # moved to the Worker's own domain and one still pointing at workers.dev —
    # is the state in which one language's form works and the other's does not.
    if len(origins) > 1:
        say("the two editions post to different places: %s" % "; ".join(
            "%s from %s" % (o, ", ".join(p)) for o, p in sorted(origins.items())))

    # 9. THE EDITIONS. The two message tables must offer the same keys: a name
    # present in one branch and missing in the other is a TypeError on submit.
    keysets = {loc: js_message_keys(validate_js, loc) for loc, _, _ in EDITIONS}
    known = {loc: k for loc, k in keysets.items() if k}
    if len(known) == len(EDITIONS):
        base_loc, base = next(iter(known.items()))
        for loc, keys in known.items():
            for missing in sorted(base - keys):
                say("validate.js's MESSAGES.%s has no %r, which MESSAGES.%s "
                    "defines — that field's error would throw on submit"
                    % (loc, missing, base_loc))
            for extra in sorted(keys - base):
                say("validate.js's MESSAGES.%s defines %r, which MESSAGES.%s "
                    "does not — one edition would say something the other "
                    "cannot" % (loc, extra, base_loc))

    # 6. THE MESSAGES.
    spec = FORMS_DOC.read_text(encoding="utf-8")
    for quote in QUOTED:
        if quote not in validate_js:
            say("validate.js no longer uses the message %r" % quote)
        elif quote not in spec:
            say("validate.js uses the message %r, which components/forms.html "
                "no longer shows — one of the two moved" % quote)

    # 7. THE ROUTES. Every path the Worker names must be a page that ships.
    for route, (locale, thanks) in sorted(routes.items()):
        for label, path in (("route", route), ("thanks page", thanks)):
            if not (ROOT / path.lstrip("/")).exists():
                say("index.js's %s %s is not a page the build ships" % (label, path))

    # 8. THE WORKER'S REACH.
    first = worker_first()
    if first is None:
        say("wrangler.toml has no readable run_worker_first")
    else:
        for route in sorted(routes):
            if route not in first:
                say("index.js answers %s, but wrangler.toml's run_worker_first "
                    "does not name it — the Worker never runs for that path and "
                    "the POST is answered by the asset server with a 200" % route)
        directories = js_directories(index_js)
        if directories is None:
            say("index.js has no readable DIRECTORIES set")
        else:
            for path in sorted(directories - first):
                say("index.js serves the directory index %s, but wrangler.toml's "
                    "run_worker_first does not name it — html_handling is "
                    '"none", so that URL 404s' % path)

    if verbose and not findings:
        for locale, _, route in EDITIONS:
            reader = readers[locale]
            print("  %s  %s" % (locale, route))
            print("      wrappers  %s" % ", ".join(sorted(reader.wrappers)))
            print("      topics    %s" % ", ".join(reader.topics()))
            print("      thanks    %s" % routes[route][1])
        print("  honeypot   %s" % HONEYPOT)

    return findings, readers


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="list every agreement audited")
    args = ap.parse_args()

    findings, readers = audit(args.verbose)

    if findings:
        print("\n".join(findings), file=sys.stderr)
        print("\n%d finding%s between the contact pages and worker/."
              % (len(findings), "" if len(findings) == 1 else "s"),
              file=sys.stderr)
        return 1

    fields = len(readers["de"].wrappers) if "de" in readers else 0
    topics = len(readers["de"].topics()) if "de" in readers else 0
    print("form contract: %d fields, %d topics and the honeypot agree across "
          "%d editions and worker/; the summary's anchor matches one form per "
          "page, every route ships and wrangler.toml runs the Worker for all "
          "of them." % (fields, topics, len(readers)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
